// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: banner.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllBannerRequest) Reset() {
	*x = FindAllBannerRequest{}
	mi := &file_banner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllBannerRequest) ProtoMessage() {}

func (x *FindAllBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllBannerRequest.ProtoReflect.Descriptor instead.
func (*FindAllBannerRequest) Descriptor() ([]byte, []int) {
	return file_banner_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllBannerRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllBannerRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllBannerRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByIdBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdBannerRequest) Reset() {
	*x = FindByIdBannerRequest{}
	mi := &file_banner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdBannerRequest) ProtoMessage() {}

func (x *FindByIdBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdBannerRequest.ProtoReflect.Descriptor instead.
func (*FindByIdBannerRequest) Descriptor() ([]byte, []int) {
	return file_banner_proto_rawDescGZIP(), []int{1}
}

func (x *FindByIdBannerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBannerRequest) Reset() {
	*x = CreateBannerRequest{}
	mi := &file_banner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBannerRequest) ProtoMessage() {}

func (x *CreateBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBannerRequest.ProtoReflect.Descriptor instead.
func (*CreateBannerRequest) Descriptor() ([]byte, []int) {
	return file_banner_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBannerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBannerRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateBannerRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CreateBannerRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateBannerRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateBannerRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateBannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BannerId      int32                  `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	StartTime     string                 `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBannerRequest) Reset() {
	*x = UpdateBannerRequest{}
	mi := &file_banner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBannerRequest) ProtoMessage() {}

func (x *UpdateBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBannerRequest.ProtoReflect.Descriptor instead.
func (*UpdateBannerRequest) Descriptor() ([]byte, []int) {
	return file_banner_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBannerRequest) GetBannerId() int32 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

func (x *UpdateBannerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBannerRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *UpdateBannerRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *UpdateBannerRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *UpdateBannerRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *UpdateBannerRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type BannerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BannerId      int32                  `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	StartTime     string                 `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerResponse) Reset() {
	*x = BannerResponse{}
	mi := &file_banner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerResponse) ProtoMessage() {}

func (x *BannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_banner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerResponse.ProtoReflect.Descriptor instead.
func (*BannerResponse) Descriptor() ([]byte, []int) {
	return file_banner_proto_rawDescGZIP(), []int{4}
}

func (x *BannerResponse) GetBannerId() int32 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

func (x *BannerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BannerResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *BannerResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *BannerResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *BannerResponse) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *BannerResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *BannerResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BannerResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BannerResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	BannerId      int32                   `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartDate     string                  `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                  `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	StartTime     string                  `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                  `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsActive      bool                    `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerResponseDeleteAt) Reset() {
	*x = BannerResponseDeleteAt{}
	mi := &file_banner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerResponseDeleteAt) ProtoMessage() {}

func (x *BannerResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_banner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*BannerResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_banner_proto_rawDescGZIP(), []int{5}
}

func (x *BannerResponseDeleteAt) GetBannerId() int32 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

func (x *BannerResponseDeleteAt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BannerResponseDeleteAt) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *BannerResponseDeleteAt) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *BannerResponseDeleteAt) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *BannerResponseDeleteAt) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *BannerResponseDeleteAt) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *BannerResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BannerResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *BannerResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseBanner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *BannerResponse        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseBanner) Reset() {
	*x = ApiResponseBanner{}
	mi := &file_banner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseBanner) ProtoMessage() {}

func (x *ApiResponseBanner) ProtoReflect() protoreflect.Message {
	mi := &file_banner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseBanner.ProtoReflect.Descriptor instead.
func (*ApiResponseBanner) Descriptor() ([]byte, []int) {
	return file_banner_proto_rawDescGZIP(), []int{6}
}

func (x *ApiResponseBanner) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseBanner) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseBanner) GetData() *BannerResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseBannerDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        string                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *BannerResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseBannerDeleteAt) Reset() {
	*x = ApiResponseBannerDeleteAt{}
	mi := &file_banner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseBannerDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseBannerDeleteAt) ProtoMessage() {}

func (x *ApiResponseBannerDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_banner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseBannerDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseBannerDeleteAt) Descriptor() ([]byte, []int) {
	return file_banner_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResponseBannerDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseBannerDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseBannerDeleteAt) GetData() *BannerResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesBanner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*BannerResponse      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesBanner) Reset() {
	*x = ApiResponsesBanner{}
	mi := &file_banner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesBanner) ProtoMessage() {}

func (x *ApiResponsesBanner) ProtoReflect() protoreflect.Message {
	mi := &file_banner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesBanner.ProtoReflect.Descriptor instead.
func (*ApiResponsesBanner) Descriptor() ([]byte, []int) {
	return file_banner_proto_rawDescGZIP(), []int{8}
}

func (x *ApiResponsesBanner) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesBanner) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesBanner) GetData() []*BannerResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseBannerDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseBannerDelete) Reset() {
	*x = ApiResponseBannerDelete{}
	mi := &file_banner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseBannerDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseBannerDelete) ProtoMessage() {}

func (x *ApiResponseBannerDelete) ProtoReflect() protoreflect.Message {
	mi := &file_banner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseBannerDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseBannerDelete) Descriptor() ([]byte, []int) {
	return file_banner_proto_rawDescGZIP(), []int{9}
}

func (x *ApiResponseBannerDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseBannerDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseBannerAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseBannerAll) Reset() {
	*x = ApiResponseBannerAll{}
	mi := &file_banner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseBannerAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseBannerAll) ProtoMessage() {}

func (x *ApiResponseBannerAll) ProtoReflect() protoreflect.Message {
	mi := &file_banner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseBannerAll.ProtoReflect.Descriptor instead.
func (*ApiResponseBannerAll) Descriptor() ([]byte, []int) {
	return file_banner_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponseBannerAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseBannerAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationBannerDeleteAt struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        string                    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*BannerResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta           `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationBannerDeleteAt) Reset() {
	*x = ApiResponsePaginationBannerDeleteAt{}
	mi := &file_banner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationBannerDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationBannerDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationBannerDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_banner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationBannerDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationBannerDeleteAt) Descriptor() ([]byte, []int) {
	return file_banner_proto_rawDescGZIP(), []int{11}
}

func (x *ApiResponsePaginationBannerDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationBannerDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationBannerDeleteAt) GetData() []*BannerResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationBannerDeleteAt) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationBanner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*BannerResponse      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationBanner) Reset() {
	*x = ApiResponsePaginationBanner{}
	mi := &file_banner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationBanner) ProtoMessage() {}

func (x *ApiResponsePaginationBanner) ProtoReflect() protoreflect.Message {
	mi := &file_banner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationBanner.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationBanner) Descriptor() ([]byte, []int) {
	return file_banner_proto_rawDescGZIP(), []int{12}
}

func (x *ApiResponsePaginationBanner) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationBanner) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationBanner) GetData() []*BannerResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationBanner) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_banner_proto protoreflect.FileDescriptor

const file_banner_proto_rawDesc = "" +
	"\n" +
	"\fbanner.proto\x12\x02pb\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\tapi.proto\"_\n" +
	"\x14FindAllBannerRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"'\n" +
	"\x15FindByIdBannerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xba\x01\n" +
	"\x13CreateBannerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"\xd7\x01\n" +
	"\x13UpdateBannerRequest\x12\x1b\n" +
	"\tbanner_id\x18\x01 \x01(\x05R\bbannerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\tR\aendTime\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"\x90\x02\n" +
	"\x0eBannerResponse\x12\x1b\n" +
	"\tbanner_id\x18\x01 \x01(\x05R\bbannerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\tR\aendTime\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xd5\x02\n" +
	"\x16BannerResponseDeleteAt\x12\x1b\n" +
	"\tbanner_id\x18\x01 \x01(\x05R\bbannerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\tR\aendTime\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"m\n" +
	"\x11ApiResponseBanner\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x01(\v2\x12.pb.BannerResponseR\x04data\"}\n" +
	"\x19ApiResponseBannerDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.pb.BannerResponseDeleteAtR\x04data\"n\n" +
	"\x12ApiResponsesBanner\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.pb.BannerResponseR\x04data\"K\n" +
	"\x17ApiResponseBannerDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x14ApiResponseBannerAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbb\x01\n" +
	"#ApiResponsePaginationBannerDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04data\x18\x03 \x03(\v2\x1a.pb.BannerResponseDeleteAtR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination\"\xab\x01\n" +
	"\x1bApiResponsePaginationBanner\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.pb.BannerResponseR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination2\xb1\x06\n" +
	"\rBannerService\x12D\n" +
	"\aFindAll\x12\x18.pb.FindAllBannerRequest\x1a\x1f.pb.ApiResponsePaginationBanner\x12<\n" +
	"\bFindById\x12\x19.pb.FindByIdBannerRequest\x1a\x15.pb.ApiResponseBanner\x12S\n" +
	"\fFindByActive\x12\x18.pb.FindAllBannerRequest\x1a'.pb.ApiResponsePaginationBannerDeleteAt\"\x00\x12T\n" +
	"\rFindByTrashed\x12\x18.pb.FindAllBannerRequest\x1a'.pb.ApiResponsePaginationBannerDeleteAt\"\x00\x128\n" +
	"\x06Create\x12\x17.pb.CreateBannerRequest\x1a\x15.pb.ApiResponseBanner\x128\n" +
	"\x06Update\x12\x17.pb.UpdateBannerRequest\x1a\x15.pb.ApiResponseBanner\x12I\n" +
	"\rTrashedBanner\x12\x19.pb.FindByIdBannerRequest\x1a\x1d.pb.ApiResponseBannerDeleteAt\x12I\n" +
	"\rRestoreBanner\x12\x19.pb.FindByIdBannerRequest\x1a\x1d.pb.ApiResponseBannerDeleteAt\x12O\n" +
	"\x15DeleteBannerPermanent\x12\x19.pb.FindByIdBannerRequest\x1a\x1b.pb.ApiResponseBannerDelete\x12F\n" +
	"\x10RestoreAllBanner\x12\x16.google.protobuf.Empty\x1a\x18.pb.ApiResponseBannerAll\"\x00\x12N\n" +
	"\x18DeleteAllBannerPermanent\x12\x16.google.protobuf.Empty\x1a\x18.pb.ApiResponseBannerAll\"\x00B9Z7github.com/MamangRust/monolith-ecommerce-shared/pbb\x06proto3"

var (
	file_banner_proto_rawDescOnce sync.Once
	file_banner_proto_rawDescData []byte
)

func file_banner_proto_rawDescGZIP() []byte {
	file_banner_proto_rawDescOnce.Do(func() {
		file_banner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_banner_proto_rawDesc), len(file_banner_proto_rawDesc)))
	})
	return file_banner_proto_rawDescData
}

var file_banner_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_banner_proto_goTypes = []any{
	(*FindAllBannerRequest)(nil),                // 0: pb.FindAllBannerRequest
	(*FindByIdBannerRequest)(nil),               // 1: pb.FindByIdBannerRequest
	(*CreateBannerRequest)(nil),                 // 2: pb.CreateBannerRequest
	(*UpdateBannerRequest)(nil),                 // 3: pb.UpdateBannerRequest
	(*BannerResponse)(nil),                      // 4: pb.BannerResponse
	(*BannerResponseDeleteAt)(nil),              // 5: pb.BannerResponseDeleteAt
	(*ApiResponseBanner)(nil),                   // 6: pb.ApiResponseBanner
	(*ApiResponseBannerDeleteAt)(nil),           // 7: pb.ApiResponseBannerDeleteAt
	(*ApiResponsesBanner)(nil),                  // 8: pb.ApiResponsesBanner
	(*ApiResponseBannerDelete)(nil),             // 9: pb.ApiResponseBannerDelete
	(*ApiResponseBannerAll)(nil),                // 10: pb.ApiResponseBannerAll
	(*ApiResponsePaginationBannerDeleteAt)(nil), // 11: pb.ApiResponsePaginationBannerDeleteAt
	(*ApiResponsePaginationBanner)(nil),         // 12: pb.ApiResponsePaginationBanner
	(*wrapperspb.StringValue)(nil),              // 13: google.protobuf.StringValue
	(*PaginationMeta)(nil),                      // 14: pb.PaginationMeta
	(*emptypb.Empty)(nil),                       // 15: google.protobuf.Empty
}
var file_banner_proto_depIdxs = []int32{
	13, // 0: pb.BannerResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	4,  // 1: pb.ApiResponseBanner.data:type_name -> pb.BannerResponse
	5,  // 2: pb.ApiResponseBannerDeleteAt.data:type_name -> pb.BannerResponseDeleteAt
	4,  // 3: pb.ApiResponsesBanner.data:type_name -> pb.BannerResponse
	5,  // 4: pb.ApiResponsePaginationBannerDeleteAt.data:type_name -> pb.BannerResponseDeleteAt
	14, // 5: pb.ApiResponsePaginationBannerDeleteAt.pagination:type_name -> pb.PaginationMeta
	4,  // 6: pb.ApiResponsePaginationBanner.data:type_name -> pb.BannerResponse
	14, // 7: pb.ApiResponsePaginationBanner.pagination:type_name -> pb.PaginationMeta
	0,  // 8: pb.BannerService.FindAll:input_type -> pb.FindAllBannerRequest
	1,  // 9: pb.BannerService.FindById:input_type -> pb.FindByIdBannerRequest
	0,  // 10: pb.BannerService.FindByActive:input_type -> pb.FindAllBannerRequest
	0,  // 11: pb.BannerService.FindByTrashed:input_type -> pb.FindAllBannerRequest
	2,  // 12: pb.BannerService.Create:input_type -> pb.CreateBannerRequest
	3,  // 13: pb.BannerService.Update:input_type -> pb.UpdateBannerRequest
	1,  // 14: pb.BannerService.TrashedBanner:input_type -> pb.FindByIdBannerRequest
	1,  // 15: pb.BannerService.RestoreBanner:input_type -> pb.FindByIdBannerRequest
	1,  // 16: pb.BannerService.DeleteBannerPermanent:input_type -> pb.FindByIdBannerRequest
	15, // 17: pb.BannerService.RestoreAllBanner:input_type -> google.protobuf.Empty
	15, // 18: pb.BannerService.DeleteAllBannerPermanent:input_type -> google.protobuf.Empty
	12, // 19: pb.BannerService.FindAll:output_type -> pb.ApiResponsePaginationBanner
	6,  // 20: pb.BannerService.FindById:output_type -> pb.ApiResponseBanner
	11, // 21: pb.BannerService.FindByActive:output_type -> pb.ApiResponsePaginationBannerDeleteAt
	11, // 22: pb.BannerService.FindByTrashed:output_type -> pb.ApiResponsePaginationBannerDeleteAt
	6,  // 23: pb.BannerService.Create:output_type -> pb.ApiResponseBanner
	6,  // 24: pb.BannerService.Update:output_type -> pb.ApiResponseBanner
	7,  // 25: pb.BannerService.TrashedBanner:output_type -> pb.ApiResponseBannerDeleteAt
	7,  // 26: pb.BannerService.RestoreBanner:output_type -> pb.ApiResponseBannerDeleteAt
	9,  // 27: pb.BannerService.DeleteBannerPermanent:output_type -> pb.ApiResponseBannerDelete
	10, // 28: pb.BannerService.RestoreAllBanner:output_type -> pb.ApiResponseBannerAll
	10, // 29: pb.BannerService.DeleteAllBannerPermanent:output_type -> pb.ApiResponseBannerAll
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_banner_proto_init() }
func file_banner_proto_init() {
	if File_banner_proto != nil {
		return
	}
	file_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_banner_proto_rawDesc), len(file_banner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_banner_proto_goTypes,
		DependencyIndexes: file_banner_proto_depIdxs,
		MessageInfos:      file_banner_proto_msgTypes,
	}.Build()
	File_banner_proto = out.File
	file_banner_proto_goTypes = nil
	file_banner_proto_depIdxs = nil
}
