// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: merchant_social_link.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MerchantSocialService_Create_FullMethodName = "/pb.MerchantSocialService/Create"
	MerchantSocialService_Update_FullMethodName = "/pb.MerchantSocialService/Update"
)

// MerchantSocialServiceClient is the client API for MerchantSocialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MerchantSocialServiceClient interface {
	Create(ctx context.Context, in *CreateMerchantSocialRequest, opts ...grpc.CallOption) (*ApiResponseMerchantSocial, error)
	Update(ctx context.Context, in *UpdateMerchantSocialRequest, opts ...grpc.CallOption) (*ApiResponseMerchantSocial, error)
}

type merchantSocialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantSocialServiceClient(cc grpc.ClientConnInterface) MerchantSocialServiceClient {
	return &merchantSocialServiceClient{cc}
}

func (c *merchantSocialServiceClient) Create(ctx context.Context, in *CreateMerchantSocialRequest, opts ...grpc.CallOption) (*ApiResponseMerchantSocial, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantSocial)
	err := c.cc.Invoke(ctx, MerchantSocialService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantSocialServiceClient) Update(ctx context.Context, in *UpdateMerchantSocialRequest, opts ...grpc.CallOption) (*ApiResponseMerchantSocial, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseMerchantSocial)
	err := c.cc.Invoke(ctx, MerchantSocialService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantSocialServiceServer is the server API for MerchantSocialService service.
// All implementations must embed UnimplementedMerchantSocialServiceServer
// for forward compatibility.
type MerchantSocialServiceServer interface {
	Create(context.Context, *CreateMerchantSocialRequest) (*ApiResponseMerchantSocial, error)
	Update(context.Context, *UpdateMerchantSocialRequest) (*ApiResponseMerchantSocial, error)
	mustEmbedUnimplementedMerchantSocialServiceServer()
}

// UnimplementedMerchantSocialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMerchantSocialServiceServer struct{}

func (UnimplementedMerchantSocialServiceServer) Create(context.Context, *CreateMerchantSocialRequest) (*ApiResponseMerchantSocial, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedMerchantSocialServiceServer) Update(context.Context, *UpdateMerchantSocialRequest) (*ApiResponseMerchantSocial, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedMerchantSocialServiceServer) mustEmbedUnimplementedMerchantSocialServiceServer() {}
func (UnimplementedMerchantSocialServiceServer) testEmbeddedByValue()                               {}

// UnsafeMerchantSocialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MerchantSocialServiceServer will
// result in compilation errors.
type UnsafeMerchantSocialServiceServer interface {
	mustEmbedUnimplementedMerchantSocialServiceServer()
}

func RegisterMerchantSocialServiceServer(s grpc.ServiceRegistrar, srv MerchantSocialServiceServer) {
	// If the following call pancis, it indicates UnimplementedMerchantSocialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MerchantSocialService_ServiceDesc, srv)
}

func _MerchantSocialService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMerchantSocialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantSocialServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantSocialService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantSocialServiceServer).Create(ctx, req.(*CreateMerchantSocialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantSocialService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMerchantSocialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantSocialServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MerchantSocialService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantSocialServiceServer).Update(ctx, req.(*UpdateMerchantSocialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MerchantSocialService_ServiceDesc is the grpc.ServiceDesc for MerchantSocialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MerchantSocialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MerchantSocialService",
	HandlerType: (*MerchantSocialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _MerchantSocialService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _MerchantSocialService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant_social_link.proto",
}
