// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: merchant_award.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllMerchantAwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllMerchantAwardRequest) Reset() {
	*x = FindAllMerchantAwardRequest{}
	mi := &file_merchant_award_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllMerchantAwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllMerchantAwardRequest) ProtoMessage() {}

func (x *FindAllMerchantAwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_award_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllMerchantAwardRequest.ProtoReflect.Descriptor instead.
func (*FindAllMerchantAwardRequest) Descriptor() ([]byte, []int) {
	return file_merchant_award_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllMerchantAwardRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllMerchantAwardRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllMerchantAwardRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByIdMerchantAwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdMerchantAwardRequest) Reset() {
	*x = FindByIdMerchantAwardRequest{}
	mi := &file_merchant_award_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdMerchantAwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdMerchantAwardRequest) ProtoMessage() {}

func (x *FindByIdMerchantAwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_award_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdMerchantAwardRequest.ProtoReflect.Descriptor instead.
func (*FindByIdMerchantAwardRequest) Descriptor() ([]byte, []int) {
	return file_merchant_award_proto_rawDescGZIP(), []int{1}
}

func (x *FindByIdMerchantAwardRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateMerchantAwardRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MerchantId     int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IssuedBy       string                 `protobuf:"bytes,4,opt,name=issued_by,json=issuedBy,proto3" json:"issued_by,omitempty"`
	IssueDate      string                 `protobuf:"bytes,5,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`
	ExpiryDate     string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	CertificateUrl string                 `protobuf:"bytes,7,opt,name=certificate_url,json=certificateUrl,proto3" json:"certificate_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateMerchantAwardRequest) Reset() {
	*x = CreateMerchantAwardRequest{}
	mi := &file_merchant_award_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantAwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantAwardRequest) ProtoMessage() {}

func (x *CreateMerchantAwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_award_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantAwardRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantAwardRequest) Descriptor() ([]byte, []int) {
	return file_merchant_award_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMerchantAwardRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CreateMerchantAwardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMerchantAwardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMerchantAwardRequest) GetIssuedBy() string {
	if x != nil {
		return x.IssuedBy
	}
	return ""
}

func (x *CreateMerchantAwardRequest) GetIssueDate() string {
	if x != nil {
		return x.IssueDate
	}
	return ""
}

func (x *CreateMerchantAwardRequest) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *CreateMerchantAwardRequest) GetCertificateUrl() string {
	if x != nil {
		return x.CertificateUrl
	}
	return ""
}

type UpdateMerchantAwardRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MerchantCertificationId int32                  `protobuf:"varint,1,opt,name=merchant_certification_id,json=merchantCertificationId,proto3" json:"merchant_certification_id,omitempty"`
	Title                   string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description             string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IssuedBy                string                 `protobuf:"bytes,4,opt,name=issued_by,json=issuedBy,proto3" json:"issued_by,omitempty"`
	IssueDate               string                 `protobuf:"bytes,5,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`
	ExpiryDate              string                 `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	CertificateUrl          string                 `protobuf:"bytes,7,opt,name=certificate_url,json=certificateUrl,proto3" json:"certificate_url,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpdateMerchantAwardRequest) Reset() {
	*x = UpdateMerchantAwardRequest{}
	mi := &file_merchant_award_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantAwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantAwardRequest) ProtoMessage() {}

func (x *UpdateMerchantAwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_award_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantAwardRequest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantAwardRequest) Descriptor() ([]byte, []int) {
	return file_merchant_award_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMerchantAwardRequest) GetMerchantCertificationId() int32 {
	if x != nil {
		return x.MerchantCertificationId
	}
	return 0
}

func (x *UpdateMerchantAwardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateMerchantAwardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMerchantAwardRequest) GetIssuedBy() string {
	if x != nil {
		return x.IssuedBy
	}
	return ""
}

func (x *UpdateMerchantAwardRequest) GetIssueDate() string {
	if x != nil {
		return x.IssueDate
	}
	return ""
}

func (x *UpdateMerchantAwardRequest) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *UpdateMerchantAwardRequest) GetCertificateUrl() string {
	if x != nil {
		return x.CertificateUrl
	}
	return ""
}

type MerchantAwardResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId     int32                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IssuedBy       string                 `protobuf:"bytes,5,opt,name=issued_by,json=issuedBy,proto3" json:"issued_by,omitempty"`
	IssueDate      string                 `protobuf:"bytes,6,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`
	ExpiryDate     string                 `protobuf:"bytes,7,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	CertificateUrl string                 `protobuf:"bytes,8,opt,name=certificate_url,json=certificateUrl,proto3" json:"certificate_url,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	MerchantName   string                 `protobuf:"bytes,11,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MerchantAwardResponse) Reset() {
	*x = MerchantAwardResponse{}
	mi := &file_merchant_award_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantAwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantAwardResponse) ProtoMessage() {}

func (x *MerchantAwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_award_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantAwardResponse.ProtoReflect.Descriptor instead.
func (*MerchantAwardResponse) Descriptor() ([]byte, []int) {
	return file_merchant_award_proto_rawDescGZIP(), []int{4}
}

func (x *MerchantAwardResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MerchantAwardResponse) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *MerchantAwardResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MerchantAwardResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MerchantAwardResponse) GetIssuedBy() string {
	if x != nil {
		return x.IssuedBy
	}
	return ""
}

func (x *MerchantAwardResponse) GetIssueDate() string {
	if x != nil {
		return x.IssueDate
	}
	return ""
}

func (x *MerchantAwardResponse) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *MerchantAwardResponse) GetCertificateUrl() string {
	if x != nil {
		return x.CertificateUrl
	}
	return ""
}

func (x *MerchantAwardResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MerchantAwardResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *MerchantAwardResponse) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

type MerchantAwardResponseDeleteAt struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Id             int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId     int32                   `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Title          string                  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IssuedBy       string                  `protobuf:"bytes,5,opt,name=issued_by,json=issuedBy,proto3" json:"issued_by,omitempty"`
	IssueDate      string                  `protobuf:"bytes,6,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`
	ExpiryDate     string                  `protobuf:"bytes,7,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	CertificateUrl string                  `protobuf:"bytes,8,opt,name=certificate_url,json=certificateUrl,proto3" json:"certificate_url,omitempty"`
	CreatedAt      string                  `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                  `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	MerchantName   string                  `protobuf:"bytes,11,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	DeletedAt      *wrapperspb.StringValue `protobuf:"bytes,12,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MerchantAwardResponseDeleteAt) Reset() {
	*x = MerchantAwardResponseDeleteAt{}
	mi := &file_merchant_award_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantAwardResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantAwardResponseDeleteAt) ProtoMessage() {}

func (x *MerchantAwardResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_award_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantAwardResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*MerchantAwardResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_merchant_award_proto_rawDescGZIP(), []int{5}
}

func (x *MerchantAwardResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MerchantAwardResponseDeleteAt) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *MerchantAwardResponseDeleteAt) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MerchantAwardResponseDeleteAt) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MerchantAwardResponseDeleteAt) GetIssuedBy() string {
	if x != nil {
		return x.IssuedBy
	}
	return ""
}

func (x *MerchantAwardResponseDeleteAt) GetIssueDate() string {
	if x != nil {
		return x.IssueDate
	}
	return ""
}

func (x *MerchantAwardResponseDeleteAt) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *MerchantAwardResponseDeleteAt) GetCertificateUrl() string {
	if x != nil {
		return x.CertificateUrl
	}
	return ""
}

func (x *MerchantAwardResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MerchantAwardResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *MerchantAwardResponseDeleteAt) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *MerchantAwardResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseMerchantAward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *MerchantAwardResponse `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantAward) Reset() {
	*x = ApiResponseMerchantAward{}
	mi := &file_merchant_award_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantAward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantAward) ProtoMessage() {}

func (x *ApiResponseMerchantAward) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_award_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantAward.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantAward) Descriptor() ([]byte, []int) {
	return file_merchant_award_proto_rawDescGZIP(), []int{6}
}

func (x *ApiResponseMerchantAward) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantAward) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMerchantAward) GetData() *MerchantAwardResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseMerchantAwardDeleteAt struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Status        string                         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *MerchantAwardResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantAwardDeleteAt) Reset() {
	*x = ApiResponseMerchantAwardDeleteAt{}
	mi := &file_merchant_award_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantAwardDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantAwardDeleteAt) ProtoMessage() {}

func (x *ApiResponseMerchantAwardDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_award_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantAwardDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantAwardDeleteAt) Descriptor() ([]byte, []int) {
	return file_merchant_award_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResponseMerchantAwardDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantAwardDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMerchantAwardDeleteAt) GetData() *MerchantAwardResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesMerchantAward struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        string                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantAwardResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesMerchantAward) Reset() {
	*x = ApiResponsesMerchantAward{}
	mi := &file_merchant_award_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesMerchantAward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesMerchantAward) ProtoMessage() {}

func (x *ApiResponsesMerchantAward) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_award_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesMerchantAward.ProtoReflect.Descriptor instead.
func (*ApiResponsesMerchantAward) Descriptor() ([]byte, []int) {
	return file_merchant_award_proto_rawDescGZIP(), []int{8}
}

func (x *ApiResponsesMerchantAward) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesMerchantAward) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesMerchantAward) GetData() []*MerchantAwardResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsePaginationMerchantAwardDeleteAt struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Status        string                           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantAwardResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta                  `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationMerchantAwardDeleteAt) Reset() {
	*x = ApiResponsePaginationMerchantAwardDeleteAt{}
	mi := &file_merchant_award_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationMerchantAwardDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationMerchantAwardDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationMerchantAwardDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_award_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationMerchantAwardDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationMerchantAwardDeleteAt) Descriptor() ([]byte, []int) {
	return file_merchant_award_proto_rawDescGZIP(), []int{9}
}

func (x *ApiResponsePaginationMerchantAwardDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationMerchantAwardDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationMerchantAwardDeleteAt) GetData() []*MerchantAwardResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationMerchantAwardDeleteAt) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationMerchantAward struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        string                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantAwardResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta          `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationMerchantAward) Reset() {
	*x = ApiResponsePaginationMerchantAward{}
	mi := &file_merchant_award_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationMerchantAward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationMerchantAward) ProtoMessage() {}

func (x *ApiResponsePaginationMerchantAward) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_award_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationMerchantAward.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationMerchantAward) Descriptor() ([]byte, []int) {
	return file_merchant_award_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponsePaginationMerchantAward) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationMerchantAward) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationMerchantAward) GetData() []*MerchantAwardResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationMerchantAward) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_merchant_award_proto protoreflect.FileDescriptor

const file_merchant_award_proto_rawDesc = "" +
	"\n" +
	"\x14merchant_award.proto\x12\x02pb\x1a\x0emerchant.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\tapi.proto\"f\n" +
	"\x1bFindAllMerchantAwardRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\".\n" +
	"\x1cFindByIdMerchantAwardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xfb\x01\n" +
	"\x1aCreateMerchantAwardRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tissued_by\x18\x04 \x01(\tR\bissuedBy\x12\x1d\n" +
	"\n" +
	"issue_date\x18\x05 \x01(\tR\tissueDate\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\x12'\n" +
	"\x0fcertificate_url\x18\a \x01(\tR\x0ecertificateUrl\"\x96\x02\n" +
	"\x1aUpdateMerchantAwardRequest\x12:\n" +
	"\x19merchant_certification_id\x18\x01 \x01(\x05R\x17merchantCertificationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tissued_by\x18\x04 \x01(\tR\bissuedBy\x12\x1d\n" +
	"\n" +
	"issue_date\x18\x05 \x01(\tR\tissueDate\x12\x1f\n" +
	"\vexpiry_date\x18\x06 \x01(\tR\n" +
	"expiryDate\x12'\n" +
	"\x0fcertificate_url\x18\a \x01(\tR\x0ecertificateUrl\"\xe9\x02\n" +
	"\x15MerchantAwardResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tissued_by\x18\x05 \x01(\tR\bissuedBy\x12\x1d\n" +
	"\n" +
	"issue_date\x18\x06 \x01(\tR\tissueDate\x12\x1f\n" +
	"\vexpiry_date\x18\a \x01(\tR\n" +
	"expiryDate\x12'\n" +
	"\x0fcertificate_url\x18\b \x01(\tR\x0ecertificateUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12#\n" +
	"\rmerchant_name\x18\v \x01(\tR\fmerchantName\"\xae\x03\n" +
	"\x1dMerchantAwardResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tissued_by\x18\x05 \x01(\tR\bissuedBy\x12\x1d\n" +
	"\n" +
	"issue_date\x18\x06 \x01(\tR\tissueDate\x12\x1f\n" +
	"\vexpiry_date\x18\a \x01(\tR\n" +
	"expiryDate\x12'\n" +
	"\x0fcertificate_url\x18\b \x01(\tR\x0ecertificateUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12#\n" +
	"\rmerchant_name\x18\v \x01(\tR\fmerchantName\x12;\n" +
	"\n" +
	"deleted_at\x18\f \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"{\n" +
	"\x18ApiResponseMerchantAward\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.pb.MerchantAwardResponseR\x04data\"\x8b\x01\n" +
	" ApiResponseMerchantAwardDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x04data\x18\x03 \x01(\v2!.pb.MerchantAwardResponseDeleteAtR\x04data\"|\n" +
	"\x19ApiResponsesMerchantAward\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x03(\v2\x19.pb.MerchantAwardResponseR\x04data\"\xc9\x01\n" +
	"*ApiResponsePaginationMerchantAwardDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x04data\x18\x03 \x03(\v2!.pb.MerchantAwardResponseDeleteAtR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination\"\xb9\x01\n" +
	"\"ApiResponsePaginationMerchantAward\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x03(\v2\x19.pb.MerchantAwardResponseR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination2\xc9\a\n" +
	"\x14MerchantAwardService\x12M\n" +
	"\aFindAll\x12\x1a.pb.FindAllMerchantRequest\x1a&.pb.ApiResponsePaginationMerchantAward\x12J\n" +
	"\bFindById\x12 .pb.FindByIdMerchantAwardRequest\x1a\x1c.pb.ApiResponseMerchantAward\x12\\\n" +
	"\fFindByActive\x12\x1a.pb.FindAllMerchantRequest\x1a..pb.ApiResponsePaginationMerchantAwardDeleteAt\"\x00\x12]\n" +
	"\rFindByTrashed\x12\x1a.pb.FindAllMerchantRequest\x1a..pb.ApiResponsePaginationMerchantAwardDeleteAt\"\x00\x12F\n" +
	"\x06Create\x12\x1e.pb.CreateMerchantAwardRequest\x1a\x1c.pb.ApiResponseMerchantAward\x12F\n" +
	"\x06Update\x12\x1e.pb.UpdateMerchantAwardRequest\x1a\x1c.pb.ApiResponseMerchantAward\x12^\n" +
	"\x14TrashedMerchantAward\x12 .pb.FindByIdMerchantAwardRequest\x1a$.pb.ApiResponseMerchantAwardDeleteAt\x12^\n" +
	"\x14RestoreMerchantAward\x12 .pb.FindByIdMerchantAwardRequest\x1a$.pb.ApiResponseMerchantAwardDeleteAt\x12_\n" +
	"\x1cDeleteMerchantAwardPermanent\x12 .pb.FindByIdMerchantAwardRequest\x1a\x1d.pb.ApiResponseMerchantDelete\x12O\n" +
	"\x17RestoreAllMerchantAward\x12\x16.google.protobuf.Empty\x1a\x1a.pb.ApiResponseMerchantAll\"\x00\x12W\n" +
	"\x1fDeleteAllMerchantAwardPermanent\x12\x16.google.protobuf.Empty\x1a\x1a.pb.ApiResponseMerchantAll\"\x00B4Z2github.com/MamangRust/monolith-ecommerce-shared/pbb\x06proto3"

var (
	file_merchant_award_proto_rawDescOnce sync.Once
	file_merchant_award_proto_rawDescData []byte
)

func file_merchant_award_proto_rawDescGZIP() []byte {
	file_merchant_award_proto_rawDescOnce.Do(func() {
		file_merchant_award_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_award_proto_rawDesc), len(file_merchant_award_proto_rawDesc)))
	})
	return file_merchant_award_proto_rawDescData
}

var file_merchant_award_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_merchant_award_proto_goTypes = []any{
	(*FindAllMerchantAwardRequest)(nil),                // 0: pb.FindAllMerchantAwardRequest
	(*FindByIdMerchantAwardRequest)(nil),               // 1: pb.FindByIdMerchantAwardRequest
	(*CreateMerchantAwardRequest)(nil),                 // 2: pb.CreateMerchantAwardRequest
	(*UpdateMerchantAwardRequest)(nil),                 // 3: pb.UpdateMerchantAwardRequest
	(*MerchantAwardResponse)(nil),                      // 4: pb.MerchantAwardResponse
	(*MerchantAwardResponseDeleteAt)(nil),              // 5: pb.MerchantAwardResponseDeleteAt
	(*ApiResponseMerchantAward)(nil),                   // 6: pb.ApiResponseMerchantAward
	(*ApiResponseMerchantAwardDeleteAt)(nil),           // 7: pb.ApiResponseMerchantAwardDeleteAt
	(*ApiResponsesMerchantAward)(nil),                  // 8: pb.ApiResponsesMerchantAward
	(*ApiResponsePaginationMerchantAwardDeleteAt)(nil), // 9: pb.ApiResponsePaginationMerchantAwardDeleteAt
	(*ApiResponsePaginationMerchantAward)(nil),         // 10: pb.ApiResponsePaginationMerchantAward
	(*wrapperspb.StringValue)(nil),                     // 11: google.protobuf.StringValue
	(*PaginationMeta)(nil),                             // 12: pb.PaginationMeta
	(*FindAllMerchantRequest)(nil),                     // 13: pb.FindAllMerchantRequest
	(*emptypb.Empty)(nil),                              // 14: google.protobuf.Empty
	(*ApiResponseMerchantDelete)(nil),                  // 15: pb.ApiResponseMerchantDelete
	(*ApiResponseMerchantAll)(nil),                     // 16: pb.ApiResponseMerchantAll
}
var file_merchant_award_proto_depIdxs = []int32{
	11, // 0: pb.MerchantAwardResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	4,  // 1: pb.ApiResponseMerchantAward.data:type_name -> pb.MerchantAwardResponse
	5,  // 2: pb.ApiResponseMerchantAwardDeleteAt.data:type_name -> pb.MerchantAwardResponseDeleteAt
	4,  // 3: pb.ApiResponsesMerchantAward.data:type_name -> pb.MerchantAwardResponse
	5,  // 4: pb.ApiResponsePaginationMerchantAwardDeleteAt.data:type_name -> pb.MerchantAwardResponseDeleteAt
	12, // 5: pb.ApiResponsePaginationMerchantAwardDeleteAt.pagination:type_name -> pb.PaginationMeta
	4,  // 6: pb.ApiResponsePaginationMerchantAward.data:type_name -> pb.MerchantAwardResponse
	12, // 7: pb.ApiResponsePaginationMerchantAward.pagination:type_name -> pb.PaginationMeta
	13, // 8: pb.MerchantAwardService.FindAll:input_type -> pb.FindAllMerchantRequest
	1,  // 9: pb.MerchantAwardService.FindById:input_type -> pb.FindByIdMerchantAwardRequest
	13, // 10: pb.MerchantAwardService.FindByActive:input_type -> pb.FindAllMerchantRequest
	13, // 11: pb.MerchantAwardService.FindByTrashed:input_type -> pb.FindAllMerchantRequest
	2,  // 12: pb.MerchantAwardService.Create:input_type -> pb.CreateMerchantAwardRequest
	3,  // 13: pb.MerchantAwardService.Update:input_type -> pb.UpdateMerchantAwardRequest
	1,  // 14: pb.MerchantAwardService.TrashedMerchantAward:input_type -> pb.FindByIdMerchantAwardRequest
	1,  // 15: pb.MerchantAwardService.RestoreMerchantAward:input_type -> pb.FindByIdMerchantAwardRequest
	1,  // 16: pb.MerchantAwardService.DeleteMerchantAwardPermanent:input_type -> pb.FindByIdMerchantAwardRequest
	14, // 17: pb.MerchantAwardService.RestoreAllMerchantAward:input_type -> google.protobuf.Empty
	14, // 18: pb.MerchantAwardService.DeleteAllMerchantAwardPermanent:input_type -> google.protobuf.Empty
	10, // 19: pb.MerchantAwardService.FindAll:output_type -> pb.ApiResponsePaginationMerchantAward
	6,  // 20: pb.MerchantAwardService.FindById:output_type -> pb.ApiResponseMerchantAward
	9,  // 21: pb.MerchantAwardService.FindByActive:output_type -> pb.ApiResponsePaginationMerchantAwardDeleteAt
	9,  // 22: pb.MerchantAwardService.FindByTrashed:output_type -> pb.ApiResponsePaginationMerchantAwardDeleteAt
	6,  // 23: pb.MerchantAwardService.Create:output_type -> pb.ApiResponseMerchantAward
	6,  // 24: pb.MerchantAwardService.Update:output_type -> pb.ApiResponseMerchantAward
	7,  // 25: pb.MerchantAwardService.TrashedMerchantAward:output_type -> pb.ApiResponseMerchantAwardDeleteAt
	7,  // 26: pb.MerchantAwardService.RestoreMerchantAward:output_type -> pb.ApiResponseMerchantAwardDeleteAt
	15, // 27: pb.MerchantAwardService.DeleteMerchantAwardPermanent:output_type -> pb.ApiResponseMerchantDelete
	16, // 28: pb.MerchantAwardService.RestoreAllMerchantAward:output_type -> pb.ApiResponseMerchantAll
	16, // 29: pb.MerchantAwardService.DeleteAllMerchantAwardPermanent:output_type -> pb.ApiResponseMerchantAll
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_merchant_award_proto_init() }
func file_merchant_award_proto_init() {
	if File_merchant_award_proto != nil {
		return
	}
	file_merchant_proto_init()
	file_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_award_proto_rawDesc), len(file_merchant_award_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_award_proto_goTypes,
		DependencyIndexes: file_merchant_award_proto_depIdxs,
		MessageInfos:      file_merchant_award_proto_msgTypes,
	}.Build()
	File_merchant_award_proto = out.File
	file_merchant_award_proto_goTypes = nil
	file_merchant_award_proto_depIdxs = nil
}
