// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: merchant_detail.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllMerchantDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllMerchantDetailRequest) Reset() {
	*x = FindAllMerchantDetailRequest{}
	mi := &file_merchant_detail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllMerchantDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllMerchantDetailRequest) ProtoMessage() {}

func (x *FindAllMerchantDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_detail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllMerchantDetailRequest.ProtoReflect.Descriptor instead.
func (*FindAllMerchantDetailRequest) Descriptor() ([]byte, []int) {
	return file_merchant_detail_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllMerchantDetailRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllMerchantDetailRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllMerchantDetailRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByIdMerchantDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdMerchantDetailRequest) Reset() {
	*x = FindByIdMerchantDetailRequest{}
	mi := &file_merchant_detail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdMerchantDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdMerchantDetailRequest) ProtoMessage() {}

func (x *FindByIdMerchantDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_detail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdMerchantDetailRequest.ProtoReflect.Descriptor instead.
func (*FindByIdMerchantDetailRequest) Descriptor() ([]byte, []int) {
	return file_merchant_detail_proto_rawDescGZIP(), []int{1}
}

func (x *FindByIdMerchantDetailRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateMerchantDetailRequest struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	MerchantId       int32                          `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	DisplayName      string                         `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	CoverImageUrl    string                         `protobuf:"bytes,3,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	LogoUrl          string                         `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	ShortDescription string                         `protobuf:"bytes,5,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	WebsiteUrl       string                         `protobuf:"bytes,6,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	SocialLinks      []*CreateMerchantSocialRequest `protobuf:"bytes,7,rep,name=social_links,json=socialLinks,proto3" json:"social_links,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateMerchantDetailRequest) Reset() {
	*x = CreateMerchantDetailRequest{}
	mi := &file_merchant_detail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantDetailRequest) ProtoMessage() {}

func (x *CreateMerchantDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_detail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantDetailRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantDetailRequest) Descriptor() ([]byte, []int) {
	return file_merchant_detail_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMerchantDetailRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CreateMerchantDetailRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateMerchantDetailRequest) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *CreateMerchantDetailRequest) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *CreateMerchantDetailRequest) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *CreateMerchantDetailRequest) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *CreateMerchantDetailRequest) GetSocialLinks() []*CreateMerchantSocialRequest {
	if x != nil {
		return x.SocialLinks
	}
	return nil
}

type UpdateMerchantDetailRequest struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	MerchantDetailId int32                          `protobuf:"varint,1,opt,name=merchant_detail_id,json=merchantDetailId,proto3" json:"merchant_detail_id,omitempty"`
	DisplayName      string                         `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	CoverImageUrl    string                         `protobuf:"bytes,3,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	LogoUrl          string                         `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	ShortDescription string                         `protobuf:"bytes,5,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	WebsiteUrl       string                         `protobuf:"bytes,6,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	SocialLinks      []*UpdateMerchantSocialRequest `protobuf:"bytes,7,rep,name=social_links,json=socialLinks,proto3" json:"social_links,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateMerchantDetailRequest) Reset() {
	*x = UpdateMerchantDetailRequest{}
	mi := &file_merchant_detail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantDetailRequest) ProtoMessage() {}

func (x *UpdateMerchantDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_detail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantDetailRequest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantDetailRequest) Descriptor() ([]byte, []int) {
	return file_merchant_detail_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMerchantDetailRequest) GetMerchantDetailId() int32 {
	if x != nil {
		return x.MerchantDetailId
	}
	return 0
}

func (x *UpdateMerchantDetailRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateMerchantDetailRequest) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *UpdateMerchantDetailRequest) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *UpdateMerchantDetailRequest) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *UpdateMerchantDetailRequest) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *UpdateMerchantDetailRequest) GetSocialLinks() []*UpdateMerchantSocialRequest {
	if x != nil {
		return x.SocialLinks
	}
	return nil
}

type CreateMerchantSocialRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MerchantDetailId int32                  `protobuf:"varint,1,opt,name=merchant_detail_id,json=merchantDetailId,proto3" json:"merchant_detail_id,omitempty"`
	Platform         string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Url              string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateMerchantSocialRequest) Reset() {
	*x = CreateMerchantSocialRequest{}
	mi := &file_merchant_detail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantSocialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantSocialRequest) ProtoMessage() {}

func (x *CreateMerchantSocialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_detail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantSocialRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantSocialRequest) Descriptor() ([]byte, []int) {
	return file_merchant_detail_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMerchantSocialRequest) GetMerchantDetailId() int32 {
	if x != nil {
		return x.MerchantDetailId
	}
	return 0
}

func (x *CreateMerchantSocialRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateMerchantSocialRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UpdateMerchantSocialRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantDetailId int32                  `protobuf:"varint,2,opt,name=merchant_detail_id,json=merchantDetailId,proto3" json:"merchant_detail_id,omitempty"`
	Platform         string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Url              string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateMerchantSocialRequest) Reset() {
	*x = UpdateMerchantSocialRequest{}
	mi := &file_merchant_detail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantSocialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantSocialRequest) ProtoMessage() {}

func (x *UpdateMerchantSocialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_detail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantSocialRequest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantSocialRequest) Descriptor() ([]byte, []int) {
	return file_merchant_detail_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMerchantSocialRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMerchantSocialRequest) GetMerchantDetailId() int32 {
	if x != nil {
		return x.MerchantDetailId
	}
	return 0
}

func (x *UpdateMerchantSocialRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UpdateMerchantSocialRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MerchantSocialMediaLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantSocialMediaLinkResponse) Reset() {
	*x = MerchantSocialMediaLinkResponse{}
	mi := &file_merchant_detail_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantSocialMediaLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantSocialMediaLinkResponse) ProtoMessage() {}

func (x *MerchantSocialMediaLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_detail_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantSocialMediaLinkResponse.ProtoReflect.Descriptor instead.
func (*MerchantSocialMediaLinkResponse) Descriptor() ([]byte, []int) {
	return file_merchant_detail_proto_rawDescGZIP(), []int{6}
}

func (x *MerchantSocialMediaLinkResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MerchantSocialMediaLinkResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *MerchantSocialMediaLinkResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MerchantDetailResponse struct {
	state            protoimpl.MessageState             `protogen:"open.v1"`
	Id               int32                              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId       int32                              `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	DisplayName      string                             `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	CoverImageUrl    string                             `protobuf:"bytes,4,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	LogoUrl          string                             `protobuf:"bytes,5,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	ShortDescription string                             `protobuf:"bytes,6,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	WebsiteUrl       string                             `protobuf:"bytes,7,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	SocialMediaLinks []*MerchantSocialMediaLinkResponse `protobuf:"bytes,8,rep,name=social_media_links,json=socialMediaLinks,proto3" json:"social_media_links,omitempty"`
	CreatedAt        string                             `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                             `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MerchantDetailResponse) Reset() {
	*x = MerchantDetailResponse{}
	mi := &file_merchant_detail_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantDetailResponse) ProtoMessage() {}

func (x *MerchantDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_detail_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantDetailResponse.ProtoReflect.Descriptor instead.
func (*MerchantDetailResponse) Descriptor() ([]byte, []int) {
	return file_merchant_detail_proto_rawDescGZIP(), []int{7}
}

func (x *MerchantDetailResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MerchantDetailResponse) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *MerchantDetailResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MerchantDetailResponse) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *MerchantDetailResponse) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *MerchantDetailResponse) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *MerchantDetailResponse) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *MerchantDetailResponse) GetSocialMediaLinks() []*MerchantSocialMediaLinkResponse {
	if x != nil {
		return x.SocialMediaLinks
	}
	return nil
}

func (x *MerchantDetailResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MerchantDetailResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type MerchantDetailResponseDeleteAt struct {
	state            protoimpl.MessageState             `protogen:"open.v1"`
	Id               int32                              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId       int32                              `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	DisplayName      string                             `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	CoverImageUrl    string                             `protobuf:"bytes,4,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	LogoUrl          string                             `protobuf:"bytes,5,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	ShortDescription string                             `protobuf:"bytes,6,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	WebsiteUrl       string                             `protobuf:"bytes,7,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	SocialMediaLinks []*MerchantSocialMediaLinkResponse `protobuf:"bytes,8,rep,name=social_media_links,json=socialMediaLinks,proto3" json:"social_media_links,omitempty"`
	CreatedAt        string                             `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                             `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt        *wrapperspb.StringValue            `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MerchantDetailResponseDeleteAt) Reset() {
	*x = MerchantDetailResponseDeleteAt{}
	mi := &file_merchant_detail_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantDetailResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantDetailResponseDeleteAt) ProtoMessage() {}

func (x *MerchantDetailResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_detail_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantDetailResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*MerchantDetailResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_merchant_detail_proto_rawDescGZIP(), []int{8}
}

func (x *MerchantDetailResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MerchantDetailResponseDeleteAt) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *MerchantDetailResponseDeleteAt) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MerchantDetailResponseDeleteAt) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *MerchantDetailResponseDeleteAt) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *MerchantDetailResponseDeleteAt) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *MerchantDetailResponseDeleteAt) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *MerchantDetailResponseDeleteAt) GetSocialMediaLinks() []*MerchantSocialMediaLinkResponse {
	if x != nil {
		return x.SocialMediaLinks
	}
	return nil
}

func (x *MerchantDetailResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MerchantDetailResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *MerchantDetailResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseMerchantDetail struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        string                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *MerchantDetailResponse `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantDetail) Reset() {
	*x = ApiResponseMerchantDetail{}
	mi := &file_merchant_detail_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantDetail) ProtoMessage() {}

func (x *ApiResponseMerchantDetail) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_detail_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantDetail.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantDetail) Descriptor() ([]byte, []int) {
	return file_merchant_detail_proto_rawDescGZIP(), []int{9}
}

func (x *ApiResponseMerchantDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMerchantDetail) GetData() *MerchantDetailResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseMerchantDetailDeleteAt struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Status        string                          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *MerchantDetailResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantDetailDeleteAt) Reset() {
	*x = ApiResponseMerchantDetailDeleteAt{}
	mi := &file_merchant_detail_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantDetailDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantDetailDeleteAt) ProtoMessage() {}

func (x *ApiResponseMerchantDetailDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_detail_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantDetailDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantDetailDeleteAt) Descriptor() ([]byte, []int) {
	return file_merchant_detail_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponseMerchantDetailDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantDetailDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMerchantDetailDeleteAt) GetData() *MerchantDetailResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesMerchantDetail struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        string                    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantDetailResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesMerchantDetail) Reset() {
	*x = ApiResponsesMerchantDetail{}
	mi := &file_merchant_detail_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesMerchantDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesMerchantDetail) ProtoMessage() {}

func (x *ApiResponsesMerchantDetail) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_detail_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesMerchantDetail.ProtoReflect.Descriptor instead.
func (*ApiResponsesMerchantDetail) Descriptor() ([]byte, []int) {
	return file_merchant_detail_proto_rawDescGZIP(), []int{11}
}

func (x *ApiResponsesMerchantDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesMerchantDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesMerchantDetail) GetData() []*MerchantDetailResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsePaginationMerchantDetail struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        string                    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantDetailResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta           `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationMerchantDetail) Reset() {
	*x = ApiResponsePaginationMerchantDetail{}
	mi := &file_merchant_detail_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationMerchantDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationMerchantDetail) ProtoMessage() {}

func (x *ApiResponsePaginationMerchantDetail) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_detail_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationMerchantDetail.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationMerchantDetail) Descriptor() ([]byte, []int) {
	return file_merchant_detail_proto_rawDescGZIP(), []int{12}
}

func (x *ApiResponsePaginationMerchantDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationMerchantDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationMerchantDetail) GetData() []*MerchantDetailResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationMerchantDetail) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationMerchantDetailDeleteAt struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        string                            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*MerchantDetailResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta                   `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationMerchantDetailDeleteAt) Reset() {
	*x = ApiResponsePaginationMerchantDetailDeleteAt{}
	mi := &file_merchant_detail_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationMerchantDetailDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationMerchantDetailDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationMerchantDetailDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_detail_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationMerchantDetailDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationMerchantDetailDeleteAt) Descriptor() ([]byte, []int) {
	return file_merchant_detail_proto_rawDescGZIP(), []int{13}
}

func (x *ApiResponsePaginationMerchantDetailDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationMerchantDetailDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationMerchantDetailDeleteAt) GetData() []*MerchantDetailResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationMerchantDetailDeleteAt) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_merchant_detail_proto protoreflect.FileDescriptor

const file_merchant_detail_proto_rawDesc = "" +
	"\n" +
	"\x15merchant_detail.proto\x12\x02pb\x1a\x0emerchant.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\tapi.proto\"g\n" +
	"\x1cFindAllMerchantDetailRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"/\n" +
	"\x1dFindByIdMerchantDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xb6\x02\n" +
	"\x1bCreateMerchantDetailRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12&\n" +
	"\x0fcover_image_url\x18\x03 \x01(\tR\rcoverImageUrl\x12\x19\n" +
	"\blogo_url\x18\x04 \x01(\tR\alogoUrl\x12+\n" +
	"\x11short_description\x18\x05 \x01(\tR\x10shortDescription\x12\x1f\n" +
	"\vwebsite_url\x18\x06 \x01(\tR\n" +
	"websiteUrl\x12B\n" +
	"\fsocial_links\x18\a \x03(\v2\x1f.pb.CreateMerchantSocialRequestR\vsocialLinks\"\xc3\x02\n" +
	"\x1bUpdateMerchantDetailRequest\x12,\n" +
	"\x12merchant_detail_id\x18\x01 \x01(\x05R\x10merchantDetailId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12&\n" +
	"\x0fcover_image_url\x18\x03 \x01(\tR\rcoverImageUrl\x12\x19\n" +
	"\blogo_url\x18\x04 \x01(\tR\alogoUrl\x12+\n" +
	"\x11short_description\x18\x05 \x01(\tR\x10shortDescription\x12\x1f\n" +
	"\vwebsite_url\x18\x06 \x01(\tR\n" +
	"websiteUrl\x12B\n" +
	"\fsocial_links\x18\a \x03(\v2\x1f.pb.UpdateMerchantSocialRequestR\vsocialLinks\"y\n" +
	"\x1bCreateMerchantSocialRequest\x12,\n" +
	"\x12merchant_detail_id\x18\x01 \x01(\x05R\x10merchantDetailId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x89\x01\n" +
	"\x1bUpdateMerchantSocialRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12,\n" +
	"\x12merchant_detail_id\x18\x02 \x01(\x05R\x10merchantDetailId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"_\n" +
	"\x1fMerchantSocialMediaLinkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x8e\x03\n" +
	"\x16MerchantDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12&\n" +
	"\x0fcover_image_url\x18\x04 \x01(\tR\rcoverImageUrl\x12\x19\n" +
	"\blogo_url\x18\x05 \x01(\tR\alogoUrl\x12+\n" +
	"\x11short_description\x18\x06 \x01(\tR\x10shortDescription\x12\x1f\n" +
	"\vwebsite_url\x18\a \x01(\tR\n" +
	"websiteUrl\x12Q\n" +
	"\x12social_media_links\x18\b \x03(\v2#.pb.MerchantSocialMediaLinkResponseR\x10socialMediaLinks\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xd3\x03\n" +
	"\x1eMerchantDetailResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x05R\n" +
	"merchantId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12&\n" +
	"\x0fcover_image_url\x18\x04 \x01(\tR\rcoverImageUrl\x12\x19\n" +
	"\blogo_url\x18\x05 \x01(\tR\alogoUrl\x12+\n" +
	"\x11short_description\x18\x06 \x01(\tR\x10shortDescription\x12\x1f\n" +
	"\vwebsite_url\x18\a \x01(\tR\n" +
	"websiteUrl\x12Q\n" +
	"\x12social_media_links\x18\b \x03(\v2#.pb.MerchantSocialMediaLinkResponseR\x10socialMediaLinks\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\v \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"}\n" +
	"\x19ApiResponseMerchantDetail\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.pb.MerchantDetailResponseR\x04data\"\x8d\x01\n" +
	"!ApiResponseMerchantDetailDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x04data\x18\x03 \x01(\v2\".pb.MerchantDetailResponseDeleteAtR\x04data\"~\n" +
	"\x1aApiResponsesMerchantDetail\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04data\x18\x03 \x03(\v2\x1a.pb.MerchantDetailResponseR\x04data\"\xbb\x01\n" +
	"#ApiResponsePaginationMerchantDetail\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04data\x18\x03 \x03(\v2\x1a.pb.MerchantDetailResponseR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination\"\xcb\x01\n" +
	"+ApiResponsePaginationMerchantDetailDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x04data\x18\x03 \x03(\v2\".pb.MerchantDetailResponseDeleteAtR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination2\xdd\a\n" +
	"\x15MerchantDetailService\x12N\n" +
	"\aFindAll\x12\x1a.pb.FindAllMerchantRequest\x1a'.pb.ApiResponsePaginationMerchantDetail\x12L\n" +
	"\bFindById\x12!.pb.FindByIdMerchantDetailRequest\x1a\x1d.pb.ApiResponseMerchantDetail\x12]\n" +
	"\fFindByActive\x12\x1a.pb.FindAllMerchantRequest\x1a/.pb.ApiResponsePaginationMerchantDetailDeleteAt\"\x00\x12^\n" +
	"\rFindByTrashed\x12\x1a.pb.FindAllMerchantRequest\x1a/.pb.ApiResponsePaginationMerchantDetailDeleteAt\"\x00\x12H\n" +
	"\x06Create\x12\x1f.pb.CreateMerchantDetailRequest\x1a\x1d.pb.ApiResponseMerchantDetail\x12H\n" +
	"\x06Update\x12\x1f.pb.UpdateMerchantDetailRequest\x1a\x1d.pb.ApiResponseMerchantDetail\x12a\n" +
	"\x15TrashedMerchantDetail\x12!.pb.FindByIdMerchantDetailRequest\x1a%.pb.ApiResponseMerchantDetailDeleteAt\x12a\n" +
	"\x15RestoreMerchantDetail\x12!.pb.FindByIdMerchantDetailRequest\x1a%.pb.ApiResponseMerchantDetailDeleteAt\x12a\n" +
	"\x1dDeleteMerchantDetailPermanent\x12!.pb.FindByIdMerchantDetailRequest\x1a\x1d.pb.ApiResponseMerchantDelete\x12P\n" +
	"\x18RestoreAllMerchantDetail\x12\x16.google.protobuf.Empty\x1a\x1a.pb.ApiResponseMerchantAll\"\x00\x12X\n" +
	" DeleteAllMerchantDetailPermanent\x12\x16.google.protobuf.Empty\x1a\x1a.pb.ApiResponseMerchantAll\"\x00B4Z2github.com/MamangRust/monolith-ecommerce-shared/pbb\x06proto3"

var (
	file_merchant_detail_proto_rawDescOnce sync.Once
	file_merchant_detail_proto_rawDescData []byte
)

func file_merchant_detail_proto_rawDescGZIP() []byte {
	file_merchant_detail_proto_rawDescOnce.Do(func() {
		file_merchant_detail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_detail_proto_rawDesc), len(file_merchant_detail_proto_rawDesc)))
	})
	return file_merchant_detail_proto_rawDescData
}

var file_merchant_detail_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_merchant_detail_proto_goTypes = []any{
	(*FindAllMerchantDetailRequest)(nil),                // 0: pb.FindAllMerchantDetailRequest
	(*FindByIdMerchantDetailRequest)(nil),               // 1: pb.FindByIdMerchantDetailRequest
	(*CreateMerchantDetailRequest)(nil),                 // 2: pb.CreateMerchantDetailRequest
	(*UpdateMerchantDetailRequest)(nil),                 // 3: pb.UpdateMerchantDetailRequest
	(*CreateMerchantSocialRequest)(nil),                 // 4: pb.CreateMerchantSocialRequest
	(*UpdateMerchantSocialRequest)(nil),                 // 5: pb.UpdateMerchantSocialRequest
	(*MerchantSocialMediaLinkResponse)(nil),             // 6: pb.MerchantSocialMediaLinkResponse
	(*MerchantDetailResponse)(nil),                      // 7: pb.MerchantDetailResponse
	(*MerchantDetailResponseDeleteAt)(nil),              // 8: pb.MerchantDetailResponseDeleteAt
	(*ApiResponseMerchantDetail)(nil),                   // 9: pb.ApiResponseMerchantDetail
	(*ApiResponseMerchantDetailDeleteAt)(nil),           // 10: pb.ApiResponseMerchantDetailDeleteAt
	(*ApiResponsesMerchantDetail)(nil),                  // 11: pb.ApiResponsesMerchantDetail
	(*ApiResponsePaginationMerchantDetail)(nil),         // 12: pb.ApiResponsePaginationMerchantDetail
	(*ApiResponsePaginationMerchantDetailDeleteAt)(nil), // 13: pb.ApiResponsePaginationMerchantDetailDeleteAt
	(*wrapperspb.StringValue)(nil),                      // 14: google.protobuf.StringValue
	(*PaginationMeta)(nil),                              // 15: pb.PaginationMeta
	(*FindAllMerchantRequest)(nil),                      // 16: pb.FindAllMerchantRequest
	(*emptypb.Empty)(nil),                               // 17: google.protobuf.Empty
	(*ApiResponseMerchantDelete)(nil),                   // 18: pb.ApiResponseMerchantDelete
	(*ApiResponseMerchantAll)(nil),                      // 19: pb.ApiResponseMerchantAll
}
var file_merchant_detail_proto_depIdxs = []int32{
	4,  // 0: pb.CreateMerchantDetailRequest.social_links:type_name -> pb.CreateMerchantSocialRequest
	5,  // 1: pb.UpdateMerchantDetailRequest.social_links:type_name -> pb.UpdateMerchantSocialRequest
	6,  // 2: pb.MerchantDetailResponse.social_media_links:type_name -> pb.MerchantSocialMediaLinkResponse
	6,  // 3: pb.MerchantDetailResponseDeleteAt.social_media_links:type_name -> pb.MerchantSocialMediaLinkResponse
	14, // 4: pb.MerchantDetailResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	7,  // 5: pb.ApiResponseMerchantDetail.data:type_name -> pb.MerchantDetailResponse
	8,  // 6: pb.ApiResponseMerchantDetailDeleteAt.data:type_name -> pb.MerchantDetailResponseDeleteAt
	7,  // 7: pb.ApiResponsesMerchantDetail.data:type_name -> pb.MerchantDetailResponse
	7,  // 8: pb.ApiResponsePaginationMerchantDetail.data:type_name -> pb.MerchantDetailResponse
	15, // 9: pb.ApiResponsePaginationMerchantDetail.pagination:type_name -> pb.PaginationMeta
	8,  // 10: pb.ApiResponsePaginationMerchantDetailDeleteAt.data:type_name -> pb.MerchantDetailResponseDeleteAt
	15, // 11: pb.ApiResponsePaginationMerchantDetailDeleteAt.pagination:type_name -> pb.PaginationMeta
	16, // 12: pb.MerchantDetailService.FindAll:input_type -> pb.FindAllMerchantRequest
	1,  // 13: pb.MerchantDetailService.FindById:input_type -> pb.FindByIdMerchantDetailRequest
	16, // 14: pb.MerchantDetailService.FindByActive:input_type -> pb.FindAllMerchantRequest
	16, // 15: pb.MerchantDetailService.FindByTrashed:input_type -> pb.FindAllMerchantRequest
	2,  // 16: pb.MerchantDetailService.Create:input_type -> pb.CreateMerchantDetailRequest
	3,  // 17: pb.MerchantDetailService.Update:input_type -> pb.UpdateMerchantDetailRequest
	1,  // 18: pb.MerchantDetailService.TrashedMerchantDetail:input_type -> pb.FindByIdMerchantDetailRequest
	1,  // 19: pb.MerchantDetailService.RestoreMerchantDetail:input_type -> pb.FindByIdMerchantDetailRequest
	1,  // 20: pb.MerchantDetailService.DeleteMerchantDetailPermanent:input_type -> pb.FindByIdMerchantDetailRequest
	17, // 21: pb.MerchantDetailService.RestoreAllMerchantDetail:input_type -> google.protobuf.Empty
	17, // 22: pb.MerchantDetailService.DeleteAllMerchantDetailPermanent:input_type -> google.protobuf.Empty
	12, // 23: pb.MerchantDetailService.FindAll:output_type -> pb.ApiResponsePaginationMerchantDetail
	9,  // 24: pb.MerchantDetailService.FindById:output_type -> pb.ApiResponseMerchantDetail
	13, // 25: pb.MerchantDetailService.FindByActive:output_type -> pb.ApiResponsePaginationMerchantDetailDeleteAt
	13, // 26: pb.MerchantDetailService.FindByTrashed:output_type -> pb.ApiResponsePaginationMerchantDetailDeleteAt
	9,  // 27: pb.MerchantDetailService.Create:output_type -> pb.ApiResponseMerchantDetail
	9,  // 28: pb.MerchantDetailService.Update:output_type -> pb.ApiResponseMerchantDetail
	10, // 29: pb.MerchantDetailService.TrashedMerchantDetail:output_type -> pb.ApiResponseMerchantDetailDeleteAt
	10, // 30: pb.MerchantDetailService.RestoreMerchantDetail:output_type -> pb.ApiResponseMerchantDetailDeleteAt
	18, // 31: pb.MerchantDetailService.DeleteMerchantDetailPermanent:output_type -> pb.ApiResponseMerchantDelete
	19, // 32: pb.MerchantDetailService.RestoreAllMerchantDetail:output_type -> pb.ApiResponseMerchantAll
	19, // 33: pb.MerchantDetailService.DeleteAllMerchantDetailPermanent:output_type -> pb.ApiResponseMerchantAll
	23, // [23:34] is the sub-list for method output_type
	12, // [12:23] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_merchant_detail_proto_init() }
func file_merchant_detail_proto_init() {
	if File_merchant_detail_proto != nil {
		return
	}
	file_merchant_proto_init()
	file_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_detail_proto_rawDesc), len(file_merchant_detail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_detail_proto_goTypes,
		DependencyIndexes: file_merchant_detail_proto_depIdxs,
		MessageInfos:      file_merchant_detail_proto_msgTypes,
	}.Build()
	File_merchant_detail_proto = out.File
	file_merchant_detail_proto_goTypes = nil
	file_merchant_detail_proto_depIdxs = nil
}
