// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: merchant_social_link.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMerchantSocialRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MerchantDetailId int32                  `protobuf:"varint,1,opt,name=merchant_detail_id,json=merchantDetailId,proto3" json:"merchant_detail_id,omitempty"`
	Platform         string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Url              string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateMerchantSocialRequest) Reset() {
	*x = CreateMerchantSocialRequest{}
	mi := &file_merchant_social_link_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMerchantSocialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMerchantSocialRequest) ProtoMessage() {}

func (x *CreateMerchantSocialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_social_link_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMerchantSocialRequest.ProtoReflect.Descriptor instead.
func (*CreateMerchantSocialRequest) Descriptor() ([]byte, []int) {
	return file_merchant_social_link_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMerchantSocialRequest) GetMerchantDetailId() int32 {
	if x != nil {
		return x.MerchantDetailId
	}
	return 0
}

func (x *CreateMerchantSocialRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateMerchantSocialRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UpdateMerchantSocialRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantDetailId int32                  `protobuf:"varint,2,opt,name=merchant_detail_id,json=merchantDetailId,proto3" json:"merchant_detail_id,omitempty"`
	Platform         string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Url              string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateMerchantSocialRequest) Reset() {
	*x = UpdateMerchantSocialRequest{}
	mi := &file_merchant_social_link_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantSocialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantSocialRequest) ProtoMessage() {}

func (x *UpdateMerchantSocialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_social_link_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantSocialRequest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantSocialRequest) Descriptor() ([]byte, []int) {
	return file_merchant_social_link_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMerchantSocialRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMerchantSocialRequest) GetMerchantDetailId() int32 {
	if x != nil {
		return x.MerchantDetailId
	}
	return 0
}

func (x *UpdateMerchantSocialRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UpdateMerchantSocialRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ApiResponseMerchantSocial struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Status        string                           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *MerchantSocialMediaLinkResponse `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMerchantSocial) Reset() {
	*x = ApiResponseMerchantSocial{}
	mi := &file_merchant_social_link_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMerchantSocial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMerchantSocial) ProtoMessage() {}

func (x *ApiResponseMerchantSocial) ProtoReflect() protoreflect.Message {
	mi := &file_merchant_social_link_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMerchantSocial.ProtoReflect.Descriptor instead.
func (*ApiResponseMerchantSocial) Descriptor() ([]byte, []int) {
	return file_merchant_social_link_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponseMerchantSocial) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMerchantSocial) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMerchantSocial) GetData() *MerchantSocialMediaLinkResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_merchant_social_link_proto protoreflect.FileDescriptor

const file_merchant_social_link_proto_rawDesc = "" +
	"\n" +
	"\x1amerchant_social_link.proto\x12\x02pb\x1a\x15merchant_detail.proto\"y\n" +
	"\x1bCreateMerchantSocialRequest\x12,\n" +
	"\x12merchant_detail_id\x18\x01 \x01(\x05R\x10merchantDetailId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x89\x01\n" +
	"\x1bUpdateMerchantSocialRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12,\n" +
	"\x12merchant_detail_id\x18\x02 \x01(\x05R\x10merchantDetailId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"\x86\x01\n" +
	"\x19ApiResponseMerchantSocial\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x01(\v2#.pb.MerchantSocialMediaLinkResponseR\x04data2\xab\x01\n" +
	"\x15MerchantSocialService\x12H\n" +
	"\x06Create\x12\x1f.pb.CreateMerchantSocialRequest\x1a\x1d.pb.ApiResponseMerchantSocial\x12H\n" +
	"\x06Update\x12\x1f.pb.UpdateMerchantSocialRequest\x1a\x1d.pb.ApiResponseMerchantSocialB4Z2github.com/MamangRust/monolith-ecommerce-shared/pbb\x06proto3"

var (
	file_merchant_social_link_proto_rawDescOnce sync.Once
	file_merchant_social_link_proto_rawDescData []byte
)

func file_merchant_social_link_proto_rawDescGZIP() []byte {
	file_merchant_social_link_proto_rawDescOnce.Do(func() {
		file_merchant_social_link_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_merchant_social_link_proto_rawDesc), len(file_merchant_social_link_proto_rawDesc)))
	})
	return file_merchant_social_link_proto_rawDescData
}

var file_merchant_social_link_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_merchant_social_link_proto_goTypes = []any{
	(*CreateMerchantSocialRequest)(nil),     // 0: pb.CreateMerchantSocialRequest
	(*UpdateMerchantSocialRequest)(nil),     // 1: pb.UpdateMerchantSocialRequest
	(*ApiResponseMerchantSocial)(nil),       // 2: pb.ApiResponseMerchantSocial
	(*MerchantSocialMediaLinkResponse)(nil), // 3: pb.MerchantSocialMediaLinkResponse
}
var file_merchant_social_link_proto_depIdxs = []int32{
	3, // 0: pb.ApiResponseMerchantSocial.data:type_name -> pb.MerchantSocialMediaLinkResponse
	0, // 1: pb.MerchantSocialService.Create:input_type -> pb.CreateMerchantSocialRequest
	1, // 2: pb.MerchantSocialService.Update:input_type -> pb.UpdateMerchantSocialRequest
	2, // 3: pb.MerchantSocialService.Create:output_type -> pb.ApiResponseMerchantSocial
	2, // 4: pb.MerchantSocialService.Update:output_type -> pb.ApiResponseMerchantSocial
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_merchant_social_link_proto_init() }
func file_merchant_social_link_proto_init() {
	if File_merchant_social_link_proto != nil {
		return
	}
	file_merchant_detail_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_merchant_social_link_proto_rawDesc), len(file_merchant_social_link_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_merchant_social_link_proto_goTypes,
		DependencyIndexes: file_merchant_social_link_proto_depIdxs,
		MessageInfos:      file_merchant_social_link_proto_msgTypes,
	}.Build()
	File_merchant_social_link_proto = out.File
	file_merchant_social_link_proto_goTypes = nil
	file_merchant_social_link_proto_depIdxs = nil
}
