// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: review.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllReviewProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllReviewProductRequest) Reset() {
	*x = FindAllReviewProductRequest{}
	mi := &file_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllReviewProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllReviewProductRequest) ProtoMessage() {}

func (x *FindAllReviewProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllReviewProductRequest.ProtoReflect.Descriptor instead.
func (*FindAllReviewProductRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllReviewProductRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *FindAllReviewProductRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllReviewProductRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllReviewProductRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindAllReviewMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllReviewMerchantRequest) Reset() {
	*x = FindAllReviewMerchantRequest{}
	mi := &file_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllReviewMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllReviewMerchantRequest) ProtoMessage() {}

func (x *FindAllReviewMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllReviewMerchantRequest.ProtoReflect.Descriptor instead.
func (*FindAllReviewMerchantRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{1}
}

func (x *FindAllReviewMerchantRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *FindAllReviewMerchantRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllReviewMerchantRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllReviewMerchantRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByIdReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdReviewRequest) Reset() {
	*x = FindByIdReviewRequest{}
	mi := &file_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdReviewRequest) ProtoMessage() {}

func (x *FindByIdReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdReviewRequest.ProtoReflect.Descriptor instead.
func (*FindByIdReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{2}
}

func (x *FindByIdReviewRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindAllReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllReviewRequest) Reset() {
	*x = FindAllReviewRequest{}
	mi := &file_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllReviewRequest) ProtoMessage() {}

func (x *FindAllReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllReviewRequest.ProtoReflect.Descriptor instead.
func (*FindAllReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{3}
}

func (x *FindAllReviewRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllReviewRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllReviewRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Rating        int32                  `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReviewRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateReviewRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateReviewRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CreateReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type UpdateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int32                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReviewRequest) Reset() {
	*x = UpdateReviewRequest{}
	mi := &file_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReviewRequest) ProtoMessage() {}

func (x *UpdateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReviewRequest.ProtoReflect.Descriptor instead.
func (*UpdateReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateReviewRequest) GetReviewId() int32 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *UpdateReviewRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *UpdateReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	Rating        int32                  `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_review_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{6}
}

func (x *ReviewResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReviewResponse) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReviewResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReviewResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ReviewResponse) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ReviewResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ReviewResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ReviewResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                   `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                  `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Comment       string                  `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	Rating        int32                   `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponseDeleteAt) Reset() {
	*x = ReviewResponseDeleteAt{}
	mi := &file_review_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponseDeleteAt) ProtoMessage() {}

func (x *ReviewResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*ReviewResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{7}
}

func (x *ReviewResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewResponseDeleteAt) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReviewResponseDeleteAt) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReviewResponseDeleteAt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReviewResponseDeleteAt) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ReviewResponseDeleteAt) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ReviewResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ReviewResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ReviewResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ReviewDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Caption       string                 `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewDetailResponse) Reset() {
	*x = ReviewDetailResponse{}
	mi := &file_review_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewDetailResponse) ProtoMessage() {}

func (x *ReviewDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewDetailResponse.ProtoReflect.Descriptor instead.
func (*ReviewDetailResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{8}
}

func (x *ReviewDetailResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewDetailResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReviewDetailResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ReviewDetailResponse) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *ReviewDetailResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ReviewsDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	Rating        int32                  `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	ReviewDetail  *ReviewDetailResponse  `protobuf:"bytes,7,opt,name=review_detail,json=reviewDetail,proto3" json:"review_detail,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewsDetailResponse) Reset() {
	*x = ReviewsDetailResponse{}
	mi := &file_review_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewsDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewsDetailResponse) ProtoMessage() {}

func (x *ReviewsDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewsDetailResponse.ProtoReflect.Descriptor instead.
func (*ReviewsDetailResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{9}
}

func (x *ReviewsDetailResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewsDetailResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReviewsDetailResponse) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReviewsDetailResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReviewsDetailResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ReviewsDetailResponse) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ReviewsDetailResponse) GetReviewDetail() *ReviewDetailResponse {
	if x != nil {
		return x.ReviewDetail
	}
	return nil
}

func (x *ReviewsDetailResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ReviewsDetailResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ReviewsDetailResponse) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type ApiResponseReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ReviewResponse        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseReview) Reset() {
	*x = ApiResponseReview{}
	mi := &file_review_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseReview) ProtoMessage() {}

func (x *ApiResponseReview) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseReview.ProtoReflect.Descriptor instead.
func (*ApiResponseReview) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponseReview) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseReview) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseReview) GetData() *ReviewResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseReviewDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        string                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ReviewResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseReviewDeleteAt) Reset() {
	*x = ApiResponseReviewDeleteAt{}
	mi := &file_review_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseReviewDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseReviewDeleteAt) ProtoMessage() {}

func (x *ApiResponseReviewDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseReviewDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseReviewDeleteAt) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{11}
}

func (x *ApiResponseReviewDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseReviewDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseReviewDeleteAt) GetData() *ReviewResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ReviewResponse      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesReview) Reset() {
	*x = ApiResponsesReview{}
	mi := &file_review_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesReview) ProtoMessage() {}

func (x *ApiResponsesReview) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesReview.ProtoReflect.Descriptor instead.
func (*ApiResponsesReview) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{12}
}

func (x *ApiResponsesReview) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesReview) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesReview) GetData() []*ReviewResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsePaginationReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ReviewResponse      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationReview) Reset() {
	*x = ApiResponsePaginationReview{}
	mi := &file_review_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationReview) ProtoMessage() {}

func (x *ApiResponsePaginationReview) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationReview.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationReview) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{13}
}

func (x *ApiResponsePaginationReview) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationReview) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationReview) GetData() []*ReviewResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationReview) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponseReviewDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseReviewDelete) Reset() {
	*x = ApiResponseReviewDelete{}
	mi := &file_review_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseReviewDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseReviewDelete) ProtoMessage() {}

func (x *ApiResponseReviewDelete) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseReviewDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseReviewDelete) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{14}
}

func (x *ApiResponseReviewDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseReviewDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseReviewAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseReviewAll) Reset() {
	*x = ApiResponseReviewAll{}
	mi := &file_review_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseReviewAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseReviewAll) ProtoMessage() {}

func (x *ApiResponseReviewAll) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseReviewAll.ProtoReflect.Descriptor instead.
func (*ApiResponseReviewAll) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{15}
}

func (x *ApiResponseReviewAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseReviewAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationReviewDeleteAt struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        string                    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ReviewResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta           `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationReviewDeleteAt) Reset() {
	*x = ApiResponsePaginationReviewDeleteAt{}
	mi := &file_review_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationReviewDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationReviewDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationReviewDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationReviewDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationReviewDeleteAt) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{16}
}

func (x *ApiResponsePaginationReviewDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationReviewDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationReviewDeleteAt) GetData() []*ReviewResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationReviewDeleteAt) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationReviewDetail struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        string                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ReviewsDetailResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta          `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationReviewDetail) Reset() {
	*x = ApiResponsePaginationReviewDetail{}
	mi := &file_review_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationReviewDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationReviewDetail) ProtoMessage() {}

func (x *ApiResponsePaginationReviewDetail) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationReviewDetail.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationReviewDetail) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{17}
}

func (x *ApiResponsePaginationReviewDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationReviewDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationReviewDetail) GetData() []*ReviewsDetailResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationReviewDetail) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_review_proto protoreflect.FileDescriptor

const file_review_proto_rawDesc = "" +
	"\n" +
	"\freview.proto\x12\x02pb\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\tapi.proto\"\x85\x01\n" +
	"\x1bFindAllReviewProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"\x88\x01\n" +
	"\x1cFindAllReviewMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"'\n" +
	"\x15FindByIdReviewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"_\n" +
	"\x14FindAllReviewRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x93\x01\n" +
	"\x13CreateReviewRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x05R\x06rating\"x\n" +
	"\x13UpdateReviewRequest\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x05R\breviewId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\"\xdc\x01\n" +
	"\x0eReviewResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x05R\x06rating\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\xa1\x02\n" +
	"\x16ReviewResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x05R\x06rating\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"\x85\x01\n" +
	"\x14ReviewDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x18\n" +
	"\acaption\x18\x04 \x01(\tR\acaption\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xc1\x02\n" +
	"\x15ReviewsDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x05R\x06rating\x12=\n" +
	"\rreview_detail\x18\a \x01(\v2\x18.pb.ReviewDetailResponseR\freviewDetail\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\tR\tdeletedAt\"m\n" +
	"\x11ApiResponseReview\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x01(\v2\x12.pb.ReviewResponseR\x04data\"}\n" +
	"\x19ApiResponseReviewDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.pb.ReviewResponseDeleteAtR\x04data\"n\n" +
	"\x12ApiResponsesReview\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.pb.ReviewResponseR\x04data\"\xab\x01\n" +
	"\x1bApiResponsePaginationReview\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.pb.ReviewResponseR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination\"K\n" +
	"\x17ApiResponseReviewDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x14ApiResponseReviewAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbb\x01\n" +
	"#ApiResponsePaginationReviewDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04data\x18\x03 \x03(\v2\x1a.pb.ReviewResponseDeleteAtR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination\"\xb8\x01\n" +
	"!ApiResponsePaginationReviewDetail\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x03(\v2\x19.pb.ReviewsDetailResponseR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination2\x9f\a\n" +
	"\rReviewService\x12D\n" +
	"\aFindAll\x12\x18.pb.FindAllReviewRequest\x1a\x1f.pb.ApiResponsePaginationReview\x12W\n" +
	"\rFindByProduct\x12\x1f.pb.FindAllReviewProductRequest\x1a%.pb.ApiResponsePaginationReviewDetail\x12Y\n" +
	"\x0eFindByMerchant\x12 .pb.FindAllReviewMerchantRequest\x1a%.pb.ApiResponsePaginationReviewDetail\x12R\n" +
	"\rFindByTrashed\x12\x18.pb.FindAllReviewRequest\x1a'.pb.ApiResponsePaginationReviewDeleteAt\x12Q\n" +
	"\fFindByActive\x12\x18.pb.FindAllReviewRequest\x1a'.pb.ApiResponsePaginationReviewDeleteAt\x128\n" +
	"\x06Create\x12\x17.pb.CreateReviewRequest\x1a\x15.pb.ApiResponseReview\x128\n" +
	"\x06Update\x12\x17.pb.UpdateReviewRequest\x1a\x15.pb.ApiResponseReview\x12I\n" +
	"\rTrashedReview\x12\x19.pb.FindByIdReviewRequest\x1a\x1d.pb.ApiResponseReviewDeleteAt\x12I\n" +
	"\rRestoreReview\x12\x19.pb.FindByIdReviewRequest\x1a\x1d.pb.ApiResponseReviewDeleteAt\x12O\n" +
	"\x15DeleteReviewPermanent\x12\x19.pb.FindByIdReviewRequest\x1a\x1b.pb.ApiResponseReviewDelete\x12D\n" +
	"\x10RestoreAllReview\x12\x16.google.protobuf.Empty\x1a\x18.pb.ApiResponseReviewAll\x12L\n" +
	"\x18DeleteAllReviewPermanent\x12\x16.google.protobuf.Empty\x1a\x18.pb.ApiResponseReviewAllB9Z7github.com/MamangRust/monolith-ecommerce-shared/pbb\x06proto3"

var (
	file_review_proto_rawDescOnce sync.Once
	file_review_proto_rawDescData []byte
)

func file_review_proto_rawDescGZIP() []byte {
	file_review_proto_rawDescOnce.Do(func() {
		file_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_proto_rawDesc), len(file_review_proto_rawDesc)))
	})
	return file_review_proto_rawDescData
}

var file_review_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_review_proto_goTypes = []any{
	(*FindAllReviewProductRequest)(nil),         // 0: pb.FindAllReviewProductRequest
	(*FindAllReviewMerchantRequest)(nil),        // 1: pb.FindAllReviewMerchantRequest
	(*FindByIdReviewRequest)(nil),               // 2: pb.FindByIdReviewRequest
	(*FindAllReviewRequest)(nil),                // 3: pb.FindAllReviewRequest
	(*CreateReviewRequest)(nil),                 // 4: pb.CreateReviewRequest
	(*UpdateReviewRequest)(nil),                 // 5: pb.UpdateReviewRequest
	(*ReviewResponse)(nil),                      // 6: pb.ReviewResponse
	(*ReviewResponseDeleteAt)(nil),              // 7: pb.ReviewResponseDeleteAt
	(*ReviewDetailResponse)(nil),                // 8: pb.ReviewDetailResponse
	(*ReviewsDetailResponse)(nil),               // 9: pb.ReviewsDetailResponse
	(*ApiResponseReview)(nil),                   // 10: pb.ApiResponseReview
	(*ApiResponseReviewDeleteAt)(nil),           // 11: pb.ApiResponseReviewDeleteAt
	(*ApiResponsesReview)(nil),                  // 12: pb.ApiResponsesReview
	(*ApiResponsePaginationReview)(nil),         // 13: pb.ApiResponsePaginationReview
	(*ApiResponseReviewDelete)(nil),             // 14: pb.ApiResponseReviewDelete
	(*ApiResponseReviewAll)(nil),                // 15: pb.ApiResponseReviewAll
	(*ApiResponsePaginationReviewDeleteAt)(nil), // 16: pb.ApiResponsePaginationReviewDeleteAt
	(*ApiResponsePaginationReviewDetail)(nil),   // 17: pb.ApiResponsePaginationReviewDetail
	(*wrapperspb.StringValue)(nil),              // 18: google.protobuf.StringValue
	(*PaginationMeta)(nil),                      // 19: pb.PaginationMeta
	(*emptypb.Empty)(nil),                       // 20: google.protobuf.Empty
}
var file_review_proto_depIdxs = []int32{
	18, // 0: pb.ReviewResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	8,  // 1: pb.ReviewsDetailResponse.review_detail:type_name -> pb.ReviewDetailResponse
	6,  // 2: pb.ApiResponseReview.data:type_name -> pb.ReviewResponse
	7,  // 3: pb.ApiResponseReviewDeleteAt.data:type_name -> pb.ReviewResponseDeleteAt
	6,  // 4: pb.ApiResponsesReview.data:type_name -> pb.ReviewResponse
	6,  // 5: pb.ApiResponsePaginationReview.data:type_name -> pb.ReviewResponse
	19, // 6: pb.ApiResponsePaginationReview.pagination:type_name -> pb.PaginationMeta
	7,  // 7: pb.ApiResponsePaginationReviewDeleteAt.data:type_name -> pb.ReviewResponseDeleteAt
	19, // 8: pb.ApiResponsePaginationReviewDeleteAt.pagination:type_name -> pb.PaginationMeta
	9,  // 9: pb.ApiResponsePaginationReviewDetail.data:type_name -> pb.ReviewsDetailResponse
	19, // 10: pb.ApiResponsePaginationReviewDetail.pagination:type_name -> pb.PaginationMeta
	3,  // 11: pb.ReviewService.FindAll:input_type -> pb.FindAllReviewRequest
	0,  // 12: pb.ReviewService.FindByProduct:input_type -> pb.FindAllReviewProductRequest
	1,  // 13: pb.ReviewService.FindByMerchant:input_type -> pb.FindAllReviewMerchantRequest
	3,  // 14: pb.ReviewService.FindByTrashed:input_type -> pb.FindAllReviewRequest
	3,  // 15: pb.ReviewService.FindByActive:input_type -> pb.FindAllReviewRequest
	4,  // 16: pb.ReviewService.Create:input_type -> pb.CreateReviewRequest
	5,  // 17: pb.ReviewService.Update:input_type -> pb.UpdateReviewRequest
	2,  // 18: pb.ReviewService.TrashedReview:input_type -> pb.FindByIdReviewRequest
	2,  // 19: pb.ReviewService.RestoreReview:input_type -> pb.FindByIdReviewRequest
	2,  // 20: pb.ReviewService.DeleteReviewPermanent:input_type -> pb.FindByIdReviewRequest
	20, // 21: pb.ReviewService.RestoreAllReview:input_type -> google.protobuf.Empty
	20, // 22: pb.ReviewService.DeleteAllReviewPermanent:input_type -> google.protobuf.Empty
	13, // 23: pb.ReviewService.FindAll:output_type -> pb.ApiResponsePaginationReview
	17, // 24: pb.ReviewService.FindByProduct:output_type -> pb.ApiResponsePaginationReviewDetail
	17, // 25: pb.ReviewService.FindByMerchant:output_type -> pb.ApiResponsePaginationReviewDetail
	16, // 26: pb.ReviewService.FindByTrashed:output_type -> pb.ApiResponsePaginationReviewDeleteAt
	16, // 27: pb.ReviewService.FindByActive:output_type -> pb.ApiResponsePaginationReviewDeleteAt
	10, // 28: pb.ReviewService.Create:output_type -> pb.ApiResponseReview
	10, // 29: pb.ReviewService.Update:output_type -> pb.ApiResponseReview
	11, // 30: pb.ReviewService.TrashedReview:output_type -> pb.ApiResponseReviewDeleteAt
	11, // 31: pb.ReviewService.RestoreReview:output_type -> pb.ApiResponseReviewDeleteAt
	14, // 32: pb.ReviewService.DeleteReviewPermanent:output_type -> pb.ApiResponseReviewDelete
	15, // 33: pb.ReviewService.RestoreAllReview:output_type -> pb.ApiResponseReviewAll
	15, // 34: pb.ReviewService.DeleteAllReviewPermanent:output_type -> pb.ApiResponseReviewAll
	23, // [23:35] is the sub-list for method output_type
	11, // [11:23] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_review_proto_init() }
func file_review_proto_init() {
	if File_review_proto != nil {
		return
	}
	file_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_proto_rawDesc), len(file_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_proto_goTypes,
		DependencyIndexes: file_review_proto_depIdxs,
		MessageInfos:      file_review_proto_msgTypes,
	}.Build()
	File_review_proto = out.File
	file_review_proto_goTypes = nil
	file_review_proto_depIdxs = nil
}
