// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: shipping_address.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindByIdShippingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdShippingRequest) Reset() {
	*x = FindByIdShippingRequest{}
	mi := &file_shipping_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdShippingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdShippingRequest) ProtoMessage() {}

func (x *FindByIdShippingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdShippingRequest.ProtoReflect.Descriptor instead.
func (*FindByIdShippingRequest) Descriptor() ([]byte, []int) {
	return file_shipping_address_proto_rawDescGZIP(), []int{0}
}

func (x *FindByIdShippingRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindAllShippingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllShippingRequest) Reset() {
	*x = FindAllShippingRequest{}
	mi := &file_shipping_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllShippingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllShippingRequest) ProtoMessage() {}

func (x *FindAllShippingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllShippingRequest.ProtoReflect.Descriptor instead.
func (*FindAllShippingRequest) Descriptor() ([]byte, []int) {
	return file_shipping_address_proto_rawDescGZIP(), []int{1}
}

func (x *FindAllShippingRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllShippingRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllShippingRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindAllShippingOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllShippingOrderRequest) Reset() {
	*x = FindAllShippingOrderRequest{}
	mi := &file_shipping_address_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllShippingOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllShippingOrderRequest) ProtoMessage() {}

func (x *FindAllShippingOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_address_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllShippingOrderRequest.ProtoReflect.Descriptor instead.
func (*FindAllShippingOrderRequest) Descriptor() ([]byte, []int) {
	return file_shipping_address_proto_rawDescGZIP(), []int{2}
}

func (x *FindAllShippingOrderRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *FindAllShippingOrderRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllShippingOrderRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllShippingOrderRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type CreateShippingAddressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Alamat         string                 `protobuf:"bytes,2,opt,name=alamat,proto3" json:"alamat,omitempty"`
	Provinsi       string                 `protobuf:"bytes,3,opt,name=provinsi,proto3" json:"provinsi,omitempty"`
	Kota           string                 `protobuf:"bytes,4,opt,name=kota,proto3" json:"kota,omitempty"`
	Courier        string                 `protobuf:"bytes,5,opt,name=courier,proto3" json:"courier,omitempty"`
	ShippingMethod string                 `protobuf:"bytes,6,opt,name=shipping_method,json=shippingMethod,proto3" json:"shipping_method,omitempty"`
	ShippingCost   int32                  `protobuf:"varint,7,opt,name=shipping_cost,json=shippingCost,proto3" json:"shipping_cost,omitempty"`
	Negara         string                 `protobuf:"bytes,8,opt,name=negara,proto3" json:"negara,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateShippingAddressRequest) Reset() {
	*x = CreateShippingAddressRequest{}
	mi := &file_shipping_address_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShippingAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShippingAddressRequest) ProtoMessage() {}

func (x *CreateShippingAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_address_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShippingAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateShippingAddressRequest) Descriptor() ([]byte, []int) {
	return file_shipping_address_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShippingAddressRequest) GetAlamat() string {
	if x != nil {
		return x.Alamat
	}
	return ""
}

func (x *CreateShippingAddressRequest) GetProvinsi() string {
	if x != nil {
		return x.Provinsi
	}
	return ""
}

func (x *CreateShippingAddressRequest) GetKota() string {
	if x != nil {
		return x.Kota
	}
	return ""
}

func (x *CreateShippingAddressRequest) GetCourier() string {
	if x != nil {
		return x.Courier
	}
	return ""
}

func (x *CreateShippingAddressRequest) GetShippingMethod() string {
	if x != nil {
		return x.ShippingMethod
	}
	return ""
}

func (x *CreateShippingAddressRequest) GetShippingCost() int32 {
	if x != nil {
		return x.ShippingCost
	}
	return 0
}

func (x *CreateShippingAddressRequest) GetNegara() string {
	if x != nil {
		return x.Negara
	}
	return ""
}

type UpdateShippingAddressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ShippingId     int32                  `protobuf:"varint,1,opt,name=shipping_id,json=shippingId,proto3" json:"shipping_id,omitempty"`
	Alamat         string                 `protobuf:"bytes,3,opt,name=alamat,proto3" json:"alamat,omitempty"`
	Provinsi       string                 `protobuf:"bytes,4,opt,name=provinsi,proto3" json:"provinsi,omitempty"`
	Kota           string                 `protobuf:"bytes,5,opt,name=kota,proto3" json:"kota,omitempty"`
	Courier        string                 `protobuf:"bytes,6,opt,name=courier,proto3" json:"courier,omitempty"`
	ShippingMethod string                 `protobuf:"bytes,7,opt,name=shipping_method,json=shippingMethod,proto3" json:"shipping_method,omitempty"`
	ShippingCost   int32                  `protobuf:"varint,8,opt,name=shipping_cost,json=shippingCost,proto3" json:"shipping_cost,omitempty"`
	Negara         string                 `protobuf:"bytes,9,opt,name=negara,proto3" json:"negara,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateShippingAddressRequest) Reset() {
	*x = UpdateShippingAddressRequest{}
	mi := &file_shipping_address_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShippingAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShippingAddressRequest) ProtoMessage() {}

func (x *UpdateShippingAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_address_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShippingAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateShippingAddressRequest) Descriptor() ([]byte, []int) {
	return file_shipping_address_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateShippingAddressRequest) GetShippingId() int32 {
	if x != nil {
		return x.ShippingId
	}
	return 0
}

func (x *UpdateShippingAddressRequest) GetAlamat() string {
	if x != nil {
		return x.Alamat
	}
	return ""
}

func (x *UpdateShippingAddressRequest) GetProvinsi() string {
	if x != nil {
		return x.Provinsi
	}
	return ""
}

func (x *UpdateShippingAddressRequest) GetKota() string {
	if x != nil {
		return x.Kota
	}
	return ""
}

func (x *UpdateShippingAddressRequest) GetCourier() string {
	if x != nil {
		return x.Courier
	}
	return ""
}

func (x *UpdateShippingAddressRequest) GetShippingMethod() string {
	if x != nil {
		return x.ShippingMethod
	}
	return ""
}

func (x *UpdateShippingAddressRequest) GetShippingCost() int32 {
	if x != nil {
		return x.ShippingCost
	}
	return 0
}

func (x *UpdateShippingAddressRequest) GetNegara() string {
	if x != nil {
		return x.Negara
	}
	return ""
}

type ShippingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId        int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Alamat         string                 `protobuf:"bytes,3,opt,name=alamat,proto3" json:"alamat,omitempty"`
	Provinsi       string                 `protobuf:"bytes,4,opt,name=provinsi,proto3" json:"provinsi,omitempty"`
	Negara         string                 `protobuf:"bytes,5,opt,name=negara,proto3" json:"negara,omitempty"`
	Kota           string                 `protobuf:"bytes,6,opt,name=kota,proto3" json:"kota,omitempty"`
	ShippingMethod string                 `protobuf:"bytes,7,opt,name=shippingMethod,proto3" json:"shippingMethod,omitempty"`
	ShippingCost   int32                  `protobuf:"varint,8,opt,name=shippingCost,proto3" json:"shippingCost,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShippingResponse) Reset() {
	*x = ShippingResponse{}
	mi := &file_shipping_address_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingResponse) ProtoMessage() {}

func (x *ShippingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_address_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingResponse.ProtoReflect.Descriptor instead.
func (*ShippingResponse) Descriptor() ([]byte, []int) {
	return file_shipping_address_proto_rawDescGZIP(), []int{5}
}

func (x *ShippingResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShippingResponse) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ShippingResponse) GetAlamat() string {
	if x != nil {
		return x.Alamat
	}
	return ""
}

func (x *ShippingResponse) GetProvinsi() string {
	if x != nil {
		return x.Provinsi
	}
	return ""
}

func (x *ShippingResponse) GetNegara() string {
	if x != nil {
		return x.Negara
	}
	return ""
}

func (x *ShippingResponse) GetKota() string {
	if x != nil {
		return x.Kota
	}
	return ""
}

func (x *ShippingResponse) GetShippingMethod() string {
	if x != nil {
		return x.ShippingMethod
	}
	return ""
}

func (x *ShippingResponse) GetShippingCost() int32 {
	if x != nil {
		return x.ShippingCost
	}
	return 0
}

func (x *ShippingResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ShippingResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ShippingResponseDeleteAt struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Id             int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId        int32                   `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Alamat         string                  `protobuf:"bytes,3,opt,name=alamat,proto3" json:"alamat,omitempty"`
	Provinsi       string                  `protobuf:"bytes,4,opt,name=provinsi,proto3" json:"provinsi,omitempty"`
	Negara         string                  `protobuf:"bytes,5,opt,name=negara,proto3" json:"negara,omitempty"`
	Kota           string                  `protobuf:"bytes,6,opt,name=kota,proto3" json:"kota,omitempty"`
	ShippingMethod string                  `protobuf:"bytes,7,opt,name=shippingMethod,proto3" json:"shippingMethod,omitempty"`
	ShippingCost   int32                   `protobuf:"varint,8,opt,name=shippingCost,proto3" json:"shippingCost,omitempty"`
	CreatedAt      string                  `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                  `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt      *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShippingResponseDeleteAt) Reset() {
	*x = ShippingResponseDeleteAt{}
	mi := &file_shipping_address_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingResponseDeleteAt) ProtoMessage() {}

func (x *ShippingResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_address_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*ShippingResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_shipping_address_proto_rawDescGZIP(), []int{6}
}

func (x *ShippingResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShippingResponseDeleteAt) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ShippingResponseDeleteAt) GetAlamat() string {
	if x != nil {
		return x.Alamat
	}
	return ""
}

func (x *ShippingResponseDeleteAt) GetProvinsi() string {
	if x != nil {
		return x.Provinsi
	}
	return ""
}

func (x *ShippingResponseDeleteAt) GetNegara() string {
	if x != nil {
		return x.Negara
	}
	return ""
}

func (x *ShippingResponseDeleteAt) GetKota() string {
	if x != nil {
		return x.Kota
	}
	return ""
}

func (x *ShippingResponseDeleteAt) GetShippingMethod() string {
	if x != nil {
		return x.ShippingMethod
	}
	return ""
}

func (x *ShippingResponseDeleteAt) GetShippingCost() int32 {
	if x != nil {
		return x.ShippingCost
	}
	return 0
}

func (x *ShippingResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ShippingResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ShippingResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseShipping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ShippingResponse      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseShipping) Reset() {
	*x = ApiResponseShipping{}
	mi := &file_shipping_address_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseShipping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseShipping) ProtoMessage() {}

func (x *ApiResponseShipping) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_address_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseShipping.ProtoReflect.Descriptor instead.
func (*ApiResponseShipping) Descriptor() ([]byte, []int) {
	return file_shipping_address_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResponseShipping) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseShipping) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseShipping) GetData() *ShippingResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseShippingDeleteAt struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        string                    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ShippingResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseShippingDeleteAt) Reset() {
	*x = ApiResponseShippingDeleteAt{}
	mi := &file_shipping_address_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseShippingDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseShippingDeleteAt) ProtoMessage() {}

func (x *ApiResponseShippingDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_address_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseShippingDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseShippingDeleteAt) Descriptor() ([]byte, []int) {
	return file_shipping_address_proto_rawDescGZIP(), []int{8}
}

func (x *ApiResponseShippingDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseShippingDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseShippingDeleteAt) GetData() *ShippingResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesShipping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ShippingResponse    `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesShipping) Reset() {
	*x = ApiResponsesShipping{}
	mi := &file_shipping_address_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesShipping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesShipping) ProtoMessage() {}

func (x *ApiResponsesShipping) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_address_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesShipping.ProtoReflect.Descriptor instead.
func (*ApiResponsesShipping) Descriptor() ([]byte, []int) {
	return file_shipping_address_proto_rawDescGZIP(), []int{9}
}

func (x *ApiResponsesShipping) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesShipping) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesShipping) GetData() []*ShippingResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseShippingDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseShippingDelete) Reset() {
	*x = ApiResponseShippingDelete{}
	mi := &file_shipping_address_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseShippingDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseShippingDelete) ProtoMessage() {}

func (x *ApiResponseShippingDelete) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_address_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseShippingDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseShippingDelete) Descriptor() ([]byte, []int) {
	return file_shipping_address_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponseShippingDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseShippingDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseShippingAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseShippingAll) Reset() {
	*x = ApiResponseShippingAll{}
	mi := &file_shipping_address_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseShippingAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseShippingAll) ProtoMessage() {}

func (x *ApiResponseShippingAll) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_address_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseShippingAll.ProtoReflect.Descriptor instead.
func (*ApiResponseShippingAll) Descriptor() ([]byte, []int) {
	return file_shipping_address_proto_rawDescGZIP(), []int{11}
}

func (x *ApiResponseShippingAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseShippingAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationShipping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ShippingResponse    `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationShipping) Reset() {
	*x = ApiResponsePaginationShipping{}
	mi := &file_shipping_address_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationShipping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationShipping) ProtoMessage() {}

func (x *ApiResponsePaginationShipping) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_address_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationShipping.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationShipping) Descriptor() ([]byte, []int) {
	return file_shipping_address_proto_rawDescGZIP(), []int{12}
}

func (x *ApiResponsePaginationShipping) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationShipping) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationShipping) GetData() []*ShippingResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationShipping) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationShippingDeleteAt struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        string                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ShippingResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta             `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationShippingDeleteAt) Reset() {
	*x = ApiResponsePaginationShippingDeleteAt{}
	mi := &file_shipping_address_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationShippingDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationShippingDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationShippingDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_address_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationShippingDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationShippingDeleteAt) Descriptor() ([]byte, []int) {
	return file_shipping_address_proto_rawDescGZIP(), []int{13}
}

func (x *ApiResponsePaginationShippingDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationShippingDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationShippingDeleteAt) GetData() []*ShippingResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationShippingDeleteAt) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_shipping_address_proto protoreflect.FileDescriptor

const file_shipping_address_proto_rawDesc = "" +
	"\n" +
	"\x16shipping_address.proto\x12\x02pb\x1a\tapi.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\")\n" +
	"\x17FindByIdShippingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"a\n" +
	"\x16FindAllShippingRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x81\x01\n" +
	"\x1bFindAllShippingOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"\xe6\x01\n" +
	"\x1cCreateShippingAddressRequest\x12\x16\n" +
	"\x06alamat\x18\x02 \x01(\tR\x06alamat\x12\x1a\n" +
	"\bprovinsi\x18\x03 \x01(\tR\bprovinsi\x12\x12\n" +
	"\x04kota\x18\x04 \x01(\tR\x04kota\x12\x18\n" +
	"\acourier\x18\x05 \x01(\tR\acourier\x12'\n" +
	"\x0fshipping_method\x18\x06 \x01(\tR\x0eshippingMethod\x12#\n" +
	"\rshipping_cost\x18\a \x01(\x05R\fshippingCost\x12\x16\n" +
	"\x06negara\x18\b \x01(\tR\x06negara\"\x87\x02\n" +
	"\x1cUpdateShippingAddressRequest\x12\x1f\n" +
	"\vshipping_id\x18\x01 \x01(\x05R\n" +
	"shippingId\x12\x16\n" +
	"\x06alamat\x18\x03 \x01(\tR\x06alamat\x12\x1a\n" +
	"\bprovinsi\x18\x04 \x01(\tR\bprovinsi\x12\x12\n" +
	"\x04kota\x18\x05 \x01(\tR\x04kota\x12\x18\n" +
	"\acourier\x18\x06 \x01(\tR\acourier\x12'\n" +
	"\x0fshipping_method\x18\a \x01(\tR\x0eshippingMethod\x12#\n" +
	"\rshipping_cost\x18\b \x01(\x05R\fshippingCost\x12\x16\n" +
	"\x06negara\x18\t \x01(\tR\x06negara\"\xa7\x02\n" +
	"\x10ShippingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x16\n" +
	"\x06alamat\x18\x03 \x01(\tR\x06alamat\x12\x1a\n" +
	"\bprovinsi\x18\x04 \x01(\tR\bprovinsi\x12\x16\n" +
	"\x06negara\x18\x05 \x01(\tR\x06negara\x12\x12\n" +
	"\x04kota\x18\x06 \x01(\tR\x04kota\x12&\n" +
	"\x0eshippingMethod\x18\a \x01(\tR\x0eshippingMethod\x12\"\n" +
	"\fshippingCost\x18\b \x01(\x05R\fshippingCost\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xec\x02\n" +
	"\x18ShippingResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x16\n" +
	"\x06alamat\x18\x03 \x01(\tR\x06alamat\x12\x1a\n" +
	"\bprovinsi\x18\x04 \x01(\tR\bprovinsi\x12\x16\n" +
	"\x06negara\x18\x05 \x01(\tR\x06negara\x12\x12\n" +
	"\x04kota\x18\x06 \x01(\tR\x04kota\x12&\n" +
	"\x0eshippingMethod\x18\a \x01(\tR\x0eshippingMethod\x12\"\n" +
	"\fshippingCost\x18\b \x01(\x05R\fshippingCost\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\v \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"q\n" +
	"\x13ApiResponseShipping\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.pb.ShippingResponseR\x04data\"\x81\x01\n" +
	"\x1bApiResponseShippingDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x04data\x18\x03 \x01(\v2\x1c.pb.ShippingResponseDeleteAtR\x04data\"r\n" +
	"\x14ApiResponsesShipping\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x03(\v2\x14.pb.ShippingResponseR\x04data\"M\n" +
	"\x19ApiResponseShippingDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"\x16ApiResponseShippingAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xaf\x01\n" +
	"\x1dApiResponsePaginationShipping\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x03(\v2\x14.pb.ShippingResponseR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination\"\xbf\x01\n" +
	"%ApiResponsePaginationShippingDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x04data\x18\x03 \x03(\v2\x1c.pb.ShippingResponseDeleteAtR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination2\xa6\x06\n" +
	"\x0fShippingService\x12H\n" +
	"\aFindAll\x12\x1a.pb.FindAllShippingRequest\x1a!.pb.ApiResponsePaginationShipping\x12@\n" +
	"\bFindById\x12\x1b.pb.FindByIdShippingRequest\x1a\x17.pb.ApiResponseShipping\x12C\n" +
	"\vFindByOrder\x12\x1b.pb.FindByIdShippingRequest\x1a\x17.pb.ApiResponseShipping\x12U\n" +
	"\fFindByActive\x12\x1a.pb.FindAllShippingRequest\x1a).pb.ApiResponsePaginationShippingDeleteAt\x12V\n" +
	"\rFindByTrashed\x12\x1a.pb.FindAllShippingRequest\x1a).pb.ApiResponsePaginationShippingDeleteAt\x12O\n" +
	"\x0fTrashedShipping\x12\x1b.pb.FindByIdShippingRequest\x1a\x1f.pb.ApiResponseShippingDeleteAt\x12O\n" +
	"\x0fRestoreShipping\x12\x1b.pb.FindByIdShippingRequest\x1a\x1f.pb.ApiResponseShippingDeleteAt\x12U\n" +
	"\x17DeleteShippingPermanent\x12\x1b.pb.FindByIdShippingRequest\x1a\x1d.pb.ApiResponseShippingDelete\x12H\n" +
	"\x12RestoreAllShipping\x12\x16.google.protobuf.Empty\x1a\x1a.pb.ApiResponseShippingAll\x12P\n" +
	"\x1aDeleteAllShippingPermanent\x12\x16.google.protobuf.Empty\x1a\x1a.pb.ApiResponseShippingAllB4Z2github.com/MamangRust/monolith-ecommerce-shared/pbb\x06proto3"

var (
	file_shipping_address_proto_rawDescOnce sync.Once
	file_shipping_address_proto_rawDescData []byte
)

func file_shipping_address_proto_rawDescGZIP() []byte {
	file_shipping_address_proto_rawDescOnce.Do(func() {
		file_shipping_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_address_proto_rawDesc), len(file_shipping_address_proto_rawDesc)))
	})
	return file_shipping_address_proto_rawDescData
}

var file_shipping_address_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_shipping_address_proto_goTypes = []any{
	(*FindByIdShippingRequest)(nil),               // 0: pb.FindByIdShippingRequest
	(*FindAllShippingRequest)(nil),                // 1: pb.FindAllShippingRequest
	(*FindAllShippingOrderRequest)(nil),           // 2: pb.FindAllShippingOrderRequest
	(*CreateShippingAddressRequest)(nil),          // 3: pb.CreateShippingAddressRequest
	(*UpdateShippingAddressRequest)(nil),          // 4: pb.UpdateShippingAddressRequest
	(*ShippingResponse)(nil),                      // 5: pb.ShippingResponse
	(*ShippingResponseDeleteAt)(nil),              // 6: pb.ShippingResponseDeleteAt
	(*ApiResponseShipping)(nil),                   // 7: pb.ApiResponseShipping
	(*ApiResponseShippingDeleteAt)(nil),           // 8: pb.ApiResponseShippingDeleteAt
	(*ApiResponsesShipping)(nil),                  // 9: pb.ApiResponsesShipping
	(*ApiResponseShippingDelete)(nil),             // 10: pb.ApiResponseShippingDelete
	(*ApiResponseShippingAll)(nil),                // 11: pb.ApiResponseShippingAll
	(*ApiResponsePaginationShipping)(nil),         // 12: pb.ApiResponsePaginationShipping
	(*ApiResponsePaginationShippingDeleteAt)(nil), // 13: pb.ApiResponsePaginationShippingDeleteAt
	(*wrapperspb.StringValue)(nil),                // 14: google.protobuf.StringValue
	(*PaginationMeta)(nil),                        // 15: pb.PaginationMeta
	(*emptypb.Empty)(nil),                         // 16: google.protobuf.Empty
}
var file_shipping_address_proto_depIdxs = []int32{
	14, // 0: pb.ShippingResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	5,  // 1: pb.ApiResponseShipping.data:type_name -> pb.ShippingResponse
	6,  // 2: pb.ApiResponseShippingDeleteAt.data:type_name -> pb.ShippingResponseDeleteAt
	5,  // 3: pb.ApiResponsesShipping.data:type_name -> pb.ShippingResponse
	5,  // 4: pb.ApiResponsePaginationShipping.data:type_name -> pb.ShippingResponse
	15, // 5: pb.ApiResponsePaginationShipping.pagination:type_name -> pb.PaginationMeta
	6,  // 6: pb.ApiResponsePaginationShippingDeleteAt.data:type_name -> pb.ShippingResponseDeleteAt
	15, // 7: pb.ApiResponsePaginationShippingDeleteAt.pagination:type_name -> pb.PaginationMeta
	1,  // 8: pb.ShippingService.FindAll:input_type -> pb.FindAllShippingRequest
	0,  // 9: pb.ShippingService.FindById:input_type -> pb.FindByIdShippingRequest
	0,  // 10: pb.ShippingService.FindByOrder:input_type -> pb.FindByIdShippingRequest
	1,  // 11: pb.ShippingService.FindByActive:input_type -> pb.FindAllShippingRequest
	1,  // 12: pb.ShippingService.FindByTrashed:input_type -> pb.FindAllShippingRequest
	0,  // 13: pb.ShippingService.TrashedShipping:input_type -> pb.FindByIdShippingRequest
	0,  // 14: pb.ShippingService.RestoreShipping:input_type -> pb.FindByIdShippingRequest
	0,  // 15: pb.ShippingService.DeleteShippingPermanent:input_type -> pb.FindByIdShippingRequest
	16, // 16: pb.ShippingService.RestoreAllShipping:input_type -> google.protobuf.Empty
	16, // 17: pb.ShippingService.DeleteAllShippingPermanent:input_type -> google.protobuf.Empty
	12, // 18: pb.ShippingService.FindAll:output_type -> pb.ApiResponsePaginationShipping
	7,  // 19: pb.ShippingService.FindById:output_type -> pb.ApiResponseShipping
	7,  // 20: pb.ShippingService.FindByOrder:output_type -> pb.ApiResponseShipping
	13, // 21: pb.ShippingService.FindByActive:output_type -> pb.ApiResponsePaginationShippingDeleteAt
	13, // 22: pb.ShippingService.FindByTrashed:output_type -> pb.ApiResponsePaginationShippingDeleteAt
	8,  // 23: pb.ShippingService.TrashedShipping:output_type -> pb.ApiResponseShippingDeleteAt
	8,  // 24: pb.ShippingService.RestoreShipping:output_type -> pb.ApiResponseShippingDeleteAt
	10, // 25: pb.ShippingService.DeleteShippingPermanent:output_type -> pb.ApiResponseShippingDelete
	11, // 26: pb.ShippingService.RestoreAllShipping:output_type -> pb.ApiResponseShippingAll
	11, // 27: pb.ShippingService.DeleteAllShippingPermanent:output_type -> pb.ApiResponseShippingAll
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_shipping_address_proto_init() }
func file_shipping_address_proto_init() {
	if File_shipping_address_proto != nil {
		return
	}
	file_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_address_proto_rawDesc), len(file_shipping_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipping_address_proto_goTypes,
		DependencyIndexes: file_shipping_address_proto_depIdxs,
		MessageInfos:      file_shipping_address_proto_msgTypes,
	}.Build()
	File_shipping_address_proto = out.File
	file_shipping_address_proto_goTypes = nil
	file_shipping_address_proto_depIdxs = nil
}
