// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: slider.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindByIdSliderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdSliderRequest) Reset() {
	*x = FindByIdSliderRequest{}
	mi := &file_slider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdSliderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdSliderRequest) ProtoMessage() {}

func (x *FindByIdSliderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdSliderRequest.ProtoReflect.Descriptor instead.
func (*FindByIdSliderRequest) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{0}
}

func (x *FindByIdSliderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindAllSliderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllSliderRequest) Reset() {
	*x = FindAllSliderRequest{}
	mi := &file_slider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllSliderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllSliderRequest) ProtoMessage() {}

func (x *FindAllSliderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllSliderRequest.ProtoReflect.Descriptor instead.
func (*FindAllSliderRequest) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{1}
}

func (x *FindAllSliderRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllSliderRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllSliderRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type CreateSliderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSliderRequest) Reset() {
	*x = CreateSliderRequest{}
	mi := &file_slider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSliderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSliderRequest) ProtoMessage() {}

func (x *CreateSliderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSliderRequest.ProtoReflect.Descriptor instead.
func (*CreateSliderRequest) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSliderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSliderRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type UpdateSliderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSliderRequest) Reset() {
	*x = UpdateSliderRequest{}
	mi := &file_slider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSliderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSliderRequest) ProtoMessage() {}

func (x *UpdateSliderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSliderRequest.ProtoReflect.Descriptor instead.
func (*UpdateSliderRequest) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSliderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSliderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSliderRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type SliderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SliderResponse) Reset() {
	*x = SliderResponse{}
	mi := &file_slider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliderResponse) ProtoMessage() {}

func (x *SliderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliderResponse.ProtoReflect.Descriptor instead.
func (*SliderResponse) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{4}
}

func (x *SliderResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SliderResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SliderResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SliderResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SliderResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SliderResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                  `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SliderResponseDeleteAt) Reset() {
	*x = SliderResponseDeleteAt{}
	mi := &file_slider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliderResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliderResponseDeleteAt) ProtoMessage() {}

func (x *SliderResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliderResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*SliderResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{5}
}

func (x *SliderResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SliderResponseDeleteAt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SliderResponseDeleteAt) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SliderResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SliderResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SliderResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseSlider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *SliderResponse        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseSlider) Reset() {
	*x = ApiResponseSlider{}
	mi := &file_slider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseSlider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseSlider) ProtoMessage() {}

func (x *ApiResponseSlider) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseSlider.ProtoReflect.Descriptor instead.
func (*ApiResponseSlider) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{6}
}

func (x *ApiResponseSlider) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseSlider) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseSlider) GetData() *SliderResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseSliderDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        string                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *SliderResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseSliderDeleteAt) Reset() {
	*x = ApiResponseSliderDeleteAt{}
	mi := &file_slider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseSliderDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseSliderDeleteAt) ProtoMessage() {}

func (x *ApiResponseSliderDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseSliderDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseSliderDeleteAt) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResponseSliderDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseSliderDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseSliderDeleteAt) GetData() *SliderResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesSlider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*SliderResponse      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesSlider) Reset() {
	*x = ApiResponsesSlider{}
	mi := &file_slider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesSlider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesSlider) ProtoMessage() {}

func (x *ApiResponsesSlider) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesSlider.ProtoReflect.Descriptor instead.
func (*ApiResponsesSlider) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{8}
}

func (x *ApiResponsesSlider) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesSlider) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesSlider) GetData() []*SliderResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseSliderDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseSliderDelete) Reset() {
	*x = ApiResponseSliderDelete{}
	mi := &file_slider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseSliderDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseSliderDelete) ProtoMessage() {}

func (x *ApiResponseSliderDelete) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseSliderDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseSliderDelete) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{9}
}

func (x *ApiResponseSliderDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseSliderDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseSliderAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseSliderAll) Reset() {
	*x = ApiResponseSliderAll{}
	mi := &file_slider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseSliderAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseSliderAll) ProtoMessage() {}

func (x *ApiResponseSliderAll) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseSliderAll.ProtoReflect.Descriptor instead.
func (*ApiResponseSliderAll) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponseSliderAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseSliderAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationSlider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*SliderResponse      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationSlider) Reset() {
	*x = ApiResponsePaginationSlider{}
	mi := &file_slider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationSlider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationSlider) ProtoMessage() {}

func (x *ApiResponsePaginationSlider) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationSlider.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationSlider) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{11}
}

func (x *ApiResponsePaginationSlider) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationSlider) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationSlider) GetData() []*SliderResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationSlider) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationSliderDeleteAt struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        string                    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*SliderResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta           `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationSliderDeleteAt) Reset() {
	*x = ApiResponsePaginationSliderDeleteAt{}
	mi := &file_slider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationSliderDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationSliderDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationSliderDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_slider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationSliderDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationSliderDeleteAt) Descriptor() ([]byte, []int) {
	return file_slider_proto_rawDescGZIP(), []int{12}
}

func (x *ApiResponsePaginationSliderDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationSliderDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationSliderDeleteAt) GetData() []*SliderResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationSliderDeleteAt) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_slider_proto protoreflect.FileDescriptor

const file_slider_proto_rawDesc = "" +
	"\n" +
	"\fslider.proto\x12\x02pb\x1a\tapi.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"'\n" +
	"\x15FindByIdSliderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"_\n" +
	"\x14FindAllSliderRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"?\n" +
	"\x13CreateSliderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\"O\n" +
	"\x13UpdateSliderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\"\x88\x01\n" +
	"\x0eSliderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"\xcd\x01\n" +
	"\x16SliderResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"m\n" +
	"\x11ApiResponseSlider\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x01(\v2\x12.pb.SliderResponseR\x04data\"}\n" +
	"\x19ApiResponseSliderDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.pb.SliderResponseDeleteAtR\x04data\"n\n" +
	"\x12ApiResponsesSlider\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.pb.SliderResponseR\x04data\"K\n" +
	"\x17ApiResponseSliderDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x14ApiResponseSliderAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xab\x01\n" +
	"\x1bApiResponsePaginationSlider\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.pb.SliderResponseR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination\"\xbb\x01\n" +
	"#ApiResponsePaginationSliderDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04data\x18\x03 \x03(\v2\x1a.pb.SliderResponseDeleteAtR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination2\xeb\x05\n" +
	"\rSliderService\x12D\n" +
	"\aFindAll\x12\x18.pb.FindAllSliderRequest\x1a\x1f.pb.ApiResponsePaginationSlider\x12R\n" +
	"\rFindByTrashed\x12\x18.pb.FindAllSliderRequest\x1a'.pb.ApiResponsePaginationSliderDeleteAt\x12Q\n" +
	"\fFindByActive\x12\x18.pb.FindAllSliderRequest\x1a'.pb.ApiResponsePaginationSliderDeleteAt\x128\n" +
	"\x06Create\x12\x17.pb.CreateSliderRequest\x1a\x15.pb.ApiResponseSlider\x128\n" +
	"\x06Update\x12\x17.pb.UpdateSliderRequest\x1a\x15.pb.ApiResponseSlider\x12I\n" +
	"\rTrashedSlider\x12\x19.pb.FindByIdSliderRequest\x1a\x1d.pb.ApiResponseSliderDeleteAt\x12I\n" +
	"\rRestoreSlider\x12\x19.pb.FindByIdSliderRequest\x1a\x1d.pb.ApiResponseSliderDeleteAt\x12O\n" +
	"\x15DeleteSliderPermanent\x12\x19.pb.FindByIdSliderRequest\x1a\x1b.pb.ApiResponseSliderDelete\x12D\n" +
	"\x10RestoreAllSlider\x12\x16.google.protobuf.Empty\x1a\x18.pb.ApiResponseSliderAll\x12L\n" +
	"\x18DeleteAllSliderPermanent\x12\x16.google.protobuf.Empty\x1a\x18.pb.ApiResponseSliderAllB4Z2github.com/MamangRust/monolith-ecommerce-shared/pbb\x06proto3"

var (
	file_slider_proto_rawDescOnce sync.Once
	file_slider_proto_rawDescData []byte
)

func file_slider_proto_rawDescGZIP() []byte {
	file_slider_proto_rawDescOnce.Do(func() {
		file_slider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slider_proto_rawDesc), len(file_slider_proto_rawDesc)))
	})
	return file_slider_proto_rawDescData
}

var file_slider_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_slider_proto_goTypes = []any{
	(*FindByIdSliderRequest)(nil),               // 0: pb.FindByIdSliderRequest
	(*FindAllSliderRequest)(nil),                // 1: pb.FindAllSliderRequest
	(*CreateSliderRequest)(nil),                 // 2: pb.CreateSliderRequest
	(*UpdateSliderRequest)(nil),                 // 3: pb.UpdateSliderRequest
	(*SliderResponse)(nil),                      // 4: pb.SliderResponse
	(*SliderResponseDeleteAt)(nil),              // 5: pb.SliderResponseDeleteAt
	(*ApiResponseSlider)(nil),                   // 6: pb.ApiResponseSlider
	(*ApiResponseSliderDeleteAt)(nil),           // 7: pb.ApiResponseSliderDeleteAt
	(*ApiResponsesSlider)(nil),                  // 8: pb.ApiResponsesSlider
	(*ApiResponseSliderDelete)(nil),             // 9: pb.ApiResponseSliderDelete
	(*ApiResponseSliderAll)(nil),                // 10: pb.ApiResponseSliderAll
	(*ApiResponsePaginationSlider)(nil),         // 11: pb.ApiResponsePaginationSlider
	(*ApiResponsePaginationSliderDeleteAt)(nil), // 12: pb.ApiResponsePaginationSliderDeleteAt
	(*wrapperspb.StringValue)(nil),              // 13: google.protobuf.StringValue
	(*PaginationMeta)(nil),                      // 14: pb.PaginationMeta
	(*emptypb.Empty)(nil),                       // 15: google.protobuf.Empty
}
var file_slider_proto_depIdxs = []int32{
	13, // 0: pb.SliderResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	4,  // 1: pb.ApiResponseSlider.data:type_name -> pb.SliderResponse
	5,  // 2: pb.ApiResponseSliderDeleteAt.data:type_name -> pb.SliderResponseDeleteAt
	4,  // 3: pb.ApiResponsesSlider.data:type_name -> pb.SliderResponse
	4,  // 4: pb.ApiResponsePaginationSlider.data:type_name -> pb.SliderResponse
	14, // 5: pb.ApiResponsePaginationSlider.pagination:type_name -> pb.PaginationMeta
	5,  // 6: pb.ApiResponsePaginationSliderDeleteAt.data:type_name -> pb.SliderResponseDeleteAt
	14, // 7: pb.ApiResponsePaginationSliderDeleteAt.pagination:type_name -> pb.PaginationMeta
	1,  // 8: pb.SliderService.FindAll:input_type -> pb.FindAllSliderRequest
	1,  // 9: pb.SliderService.FindByTrashed:input_type -> pb.FindAllSliderRequest
	1,  // 10: pb.SliderService.FindByActive:input_type -> pb.FindAllSliderRequest
	2,  // 11: pb.SliderService.Create:input_type -> pb.CreateSliderRequest
	3,  // 12: pb.SliderService.Update:input_type -> pb.UpdateSliderRequest
	0,  // 13: pb.SliderService.TrashedSlider:input_type -> pb.FindByIdSliderRequest
	0,  // 14: pb.SliderService.RestoreSlider:input_type -> pb.FindByIdSliderRequest
	0,  // 15: pb.SliderService.DeleteSliderPermanent:input_type -> pb.FindByIdSliderRequest
	15, // 16: pb.SliderService.RestoreAllSlider:input_type -> google.protobuf.Empty
	15, // 17: pb.SliderService.DeleteAllSliderPermanent:input_type -> google.protobuf.Empty
	11, // 18: pb.SliderService.FindAll:output_type -> pb.ApiResponsePaginationSlider
	12, // 19: pb.SliderService.FindByTrashed:output_type -> pb.ApiResponsePaginationSliderDeleteAt
	12, // 20: pb.SliderService.FindByActive:output_type -> pb.ApiResponsePaginationSliderDeleteAt
	6,  // 21: pb.SliderService.Create:output_type -> pb.ApiResponseSlider
	6,  // 22: pb.SliderService.Update:output_type -> pb.ApiResponseSlider
	7,  // 23: pb.SliderService.TrashedSlider:output_type -> pb.ApiResponseSliderDeleteAt
	7,  // 24: pb.SliderService.RestoreSlider:output_type -> pb.ApiResponseSliderDeleteAt
	9,  // 25: pb.SliderService.DeleteSliderPermanent:output_type -> pb.ApiResponseSliderDelete
	10, // 26: pb.SliderService.RestoreAllSlider:output_type -> pb.ApiResponseSliderAll
	10, // 27: pb.SliderService.DeleteAllSliderPermanent:output_type -> pb.ApiResponseSliderAll
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_slider_proto_init() }
func file_slider_proto_init() {
	if File_slider_proto != nil {
		return
	}
	file_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slider_proto_rawDesc), len(file_slider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_slider_proto_goTypes,
		DependencyIndexes: file_slider_proto_depIdxs,
		MessageInfos:      file_slider_proto_msgTypes,
	}.Build()
	File_slider_proto = out.File
	file_slider_proto_goTypes = nil
	file_slider_proto_depIdxs = nil
}
